use blitz_traits::net::{Request, Url};
use dioxus_native::prelude::*;

pub type SyncStore<T> = Store<T, CopyValue<T, SyncStorage>>;

#[derive(Store)]
pub struct History {
    urls: Vec<Request>,
    titles: Vec<Option<String>>,
    current: usize,
}

impl History {
    pub fn new(initial_url: Url) -> Self {
        Self {
            urls: vec![Request::get(initial_url)],
            titles: vec![None],
            current: 0,
        }
    }
}

#[store]
impl<Lens> Store<History, Lens> {
    fn current_idx(&self) -> usize {
        *self.current().read()
    }

    fn current_url(&self) -> impl Readable<Target = Request> {
        #[allow(clippy::unwrap_used)]
        // current_idx is always a valid index: urls is non-empty and current <= len-1
        self.urls().get(self.current_idx()).unwrap()
    }

    fn has_back(&self) -> bool {
        self.current_idx() > 0
    }

    fn has_forward(&self) -> bool {
        self.current_idx().saturating_add(1) < self.urls().len()
    }

    fn go_back(&mut self) {
        if self.has_back() {
            *self.current().write() = self.current_idx().saturating_sub(1);
        }
    }

    fn go_forward(&mut self) {
        if self.has_forward() {
            *self.current().write() = self.current_idx().saturating_add(1);
        }
    }

    fn navigate(&self, req: Request)
    where
        Lens: Writable,
    {
        let new_idx = self.current_idx().saturating_add(1);
        self.urls().write().truncate(new_idx);
        self.urls().push(req);
        self.titles().write().truncate(new_idx);
        self.titles().push(None);
        *self.current().write() = new_idx;
    }

    fn set_current_title(&self, title: String)
    where
        Lens: Writable,
    {
        let idx = self.current_idx();
        if let Some(t) = self.titles().write().get_mut(idx) {
            *t = Some(title);
        }
    }
}

/// Public extension trait exposing history navigation for use across modules.
/// Delegates to the private `HistoryStoreImplExt` generated by `#[store]`,
/// which is only accessible within this module.
pub trait HistoryNav {
    fn current_url(&self) -> impl Readable<Target = Request>;
    fn has_back(&self) -> bool;
    fn has_forward(&self) -> bool;
    fn go_back(&mut self);
    fn go_forward(&mut self);
    fn navigate(&self, req: Request);
    fn set_current_title(&self, title: String);
}

impl HistoryNav for SyncStore<History> {
    fn current_url(&self) -> impl Readable<Target = Request> {
        HistoryStoreImplExt::current_url(self)
    }

    fn has_back(&self) -> bool {
        HistoryStoreImplExt::has_back(self)
    }

    fn has_forward(&self) -> bool {
        HistoryStoreImplExt::has_forward(self)
    }

    fn go_back(&mut self) {
        HistoryStoreImplExt::go_back(self)
    }

    fn go_forward(&mut self) {
        HistoryStoreImplExt::go_forward(self)
    }

    fn navigate(&self, req: Request) {
        HistoryStoreImplExt::navigate(self, req)
    }

    fn set_current_title(&self, title: String) {
        HistoryStoreImplExt::set_current_title(self, title)
    }
}
