#!/usr/bin/env python3
"""Summarise the output of `wpt diff` and publish it into the PR description.

The section is delimited by HTML comment markers so that re-runs of the
workflow replace the previous results instead of appending a new section.
"""

import argparse
import json
import os
import re
import subprocess
import sys

START_MARKER = "<!-- wpt-results-start -->"
END_MARKER = "<!-- wpt-results-end -->"

PASSING_STATUSES = {"PASS", "OK"}
MAX_DIFF_LINES = 400

CHANGE_RE = re.compile(r"^(\w+) => (\w+) (.*)$")
ADD_REM_RE = re.compile(r"^(ADD|REM)\s+(.*)$")


class Diff:
    def __init__(self):
        self.newly_passing = []
        self.newly_failing = []
        self.other_changes = []
        self.added = []
        self.removed = []

    @property
    def is_empty(self):
        return not (
            self.newly_passing
            or self.newly_failing
            or self.other_changes
            or self.added
            or self.removed
        )


def parse_diff(text):
    diff = Diff()
    for line in text.splitlines():
        line = line.rstrip()
        if not line or line.startswith("=====") or line.startswith("Done in "):
            continue

        match = ADD_REM_RE.match(line)
        if match:
            kind, test = match.groups()
            (diff.added if kind == "ADD" else diff.removed).append(test)
            continue

        match = CHANGE_RE.match(line)
        if match:
            before, after, test = match.groups()
            entry = (before, after, test)
            if before.upper() not in PASSING_STATUSES and after.upper() in PASSING_STATUSES:
                diff.newly_passing.append(entry)
            elif before.upper() in PASSING_STATUSES and after.upper() not in PASSING_STATUSES:
                diff.newly_failing.append(entry)
            else:
                diff.other_changes.append(entry)

    return diff


def format_lines(diff):
    """Render the changes as diff-syntax lines sorted by test name."""
    lines = []
    for marker, entries in [("+", diff.newly_passing), ("-", diff.newly_failing), ("!", diff.other_changes)]:
        for before, after, test in entries:
            lines.append((test, f"{marker} {before} => {after} {test}"))
    lines.extend((test, f"+ ADD {test}") for test in diff.added)
    lines.extend((test, f"- REM {test}") for test in diff.removed)
    lines.sort()
    return [line for _, line in lines]


def render(diff, run_url):
    net = len(diff.newly_passing) - len(diff.newly_failing)
    if diff.is_empty:
        headline = "No changes in test results compared to `main`."
    else:
        sign = "+" if net > 0 else ""
        parts = [
            f"**{len(diff.newly_passing)}** newly passing",
            f"**{len(diff.newly_failing)}** newly failing (net {sign}{net})",
        ]
        for count, label in [
            (len(diff.other_changes), "other status change"),
            (len(diff.added), "added test"),
            (len(diff.removed), "removed test"),
        ]:
            if count:
                parts.append(f"**{count}** {label}{'s' if count != 1 else ''}")
        headline = ", ".join(parts) + "."

    out = [START_MARKER, "## WPT results", "", headline, ""]

    if not diff.is_empty:
        lines = format_lines(diff)
        truncated = len(lines) > MAX_DIFF_LINES
        shown = lines[:MAX_DIFF_LINES]
        out.append("<details>")
        out.append(f"<summary>Full diff ({len(lines)} changed tests)</summary>")
        out.append("")
        out.append("```diff")
        out.extend(shown)
        if truncated:
            out.append(f"# ... and {len(lines) - len(shown)} more (see the workflow logs)")
        out.append("```")
        out.append("")
        out.append("</details>")
        out.append("")

    if run_url:
        out.append(f"<sub>Generated by the [WPT workflow]({run_url}).</sub>")
    out.append(END_MARKER)

    return "\n".join(out)


def splice(body, section):
    body = body or ""
    start = body.find(START_MARKER)
    end = body.find(END_MARKER)
    if start != -1 and end != -1 and end > start:
        return body[:start] + section + body[end + len(END_MARKER):]
    if body.strip():
        return body.rstrip() + "\n\n" + section + "\n"
    return section + "\n"


def gh_api(*args, method=None, fields=None):
    cmd = ["gh", "api"]
    if method:
        cmd += ["-X", method]
    cmd += list(args)
    for key, value in (fields or {}).items():
        cmd += ["-f", f"{key}={value}"]
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("diff_file")
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"))
    parser.add_argument("--pr", default=os.environ.get("PR_NUMBER"))
    parser.add_argument("--run-url", default=os.environ.get("RUN_URL"))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    with open(args.diff_file, encoding="utf-8") as file:
        diff = parse_diff(file.read())

    section = render(diff, args.run_url)

    step_summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if step_summary:
        with open(step_summary, "a", encoding="utf-8") as file:
            file.write(section + "\n")

    if args.dry_run or not args.pr:
        print(section)
        return 0

    body = json.loads(gh_api(f"repos/{args.repo}/pulls/{args.pr}")).get("body") or ""
    gh_api(
        f"repos/{args.repo}/pulls/{args.pr}",
        method="PATCH",
        fields={"body": splice(body, section)},
    )
    print(f"Updated the description of PR #{args.pr}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
