use crate::{BaseDocument, DocumentMutator};
use blitz_traits::DomEvent;
use std::collections::VecDeque;

#[derive(Default)]
pub struct EventState {
    cancelled: bool,
    propagation_stopped: bool,
}
impl EventState {
    #[inline(always)]
    pub fn prevent_default(&mut self) {
        self.cancelled = true;
    }

    #[inline(always)]
    pub fn stop_propagation(&mut self) {
        self.propagation_stopped = true;
    }

    #[inline(always)]
    pub fn is_cancelled(&self) -> bool {
        self.cancelled
    }

    #[inline(always)]
    pub fn propagation_is_stopped(&self) -> bool {
        self.propagation_stopped
    }
}

pub trait EventHandler {
    fn handle_event(
        &mut self,
        node_id: usize,
        event: &mut DomEvent,
        mutr: &mut DocumentMutator<'_>,
        event_state: &mut EventState,
    );
}

pub struct EventDriver<'doc, Handler: EventHandler> {
    mutr: DocumentMutator<'doc>,
    handler: Handler,
}

impl<'doc, Handler: EventHandler> EventDriver<'doc, Handler> {
    fn doc_mut(&mut self) -> &mut BaseDocument {
        self.mutr.doc
    }

    fn doc(&self) -> &BaseDocument {
        &*self.mutr.doc
    }

    pub fn new(mutr: DocumentMutator<'doc>, handler: Handler) -> Self {
        EventDriver { mutr, handler }
    }

    pub fn handle_event(&mut self, event: &mut DomEvent) {
        let mut queue = VecDeque::with_capacity(4);
        queue.push_back(event);

        while let Some(event) = queue.pop_front() {
            let chain = self.doc().node_chain(event.target);

            let mut event_state = EventState::default();
            for node_id in chain.clone().into_iter() {
                self.handler
                    .handle_event(node_id, event, &mut self.mutr, &mut event_state);
                if !event.bubbles | event_state.propagation_is_stopped() {
                    break;
                }
            }

            if !event_state.is_cancelled() {
                self.doc_mut().handle_event(event);

                // TODO: allow events to be generated by handler(s)
                // let generated_events = self.doc_mut().handle_event(event);
                // queue.ex(&generated_events);
            }
        }
    }
}
