//! Anonymous table box construction / fixups (CSS 2.2 §17.2.1).
//!
//! - Consecutive non-table-internal children of a table share a single
//!   anonymous table cell (so they stack vertically in one column).
//! - Table cells occurring directly under a table are wrapped in an
//!   anonymous table row.
//! - Table-internal boxes (cells, rows) occurring outside a table are
//!   wrapped in an anonymous table box.
//! - The anonymous nodes generated by these fixups must not leak across
//!   reconstructions or incremental mutations.

use blitz_dom::DocumentConfig;
use blitz_html::{HtmlDocument, HtmlProvider};
use blitz_test_harness::{Harness, HarnessOptions};
use blitz_traits::shell::{ColorScheme, Viewport};
use std::sync::Arc;

fn harness(html: &str) -> Harness {
    Harness::from_html_with(
        html,
        HarnessOptions {
            width: 400,
            height: 200,
            ..Default::default()
        },
    )
}

fn document(html: &str) -> HtmlDocument {
    HtmlDocument::from_html(
        html,
        DocumentConfig {
            viewport: Some(Viewport::new(400, 200, 1.0, ColorScheme::Light)),
            html_parser_provider: Some(Arc::new(HtmlProvider) as _),
            ..Default::default()
        },
    )
}

/// Consecutive misplaced (non-table-internal) children share one anonymous
/// cell: they lay out as flow content in a single column, stacking
/// vertically, rather than each becoming its own cell/column.
#[test]
fn consecutive_misplaced_children_share_one_anonymous_cell() {
    let harness = harness(
        r#"<html><body style="margin:0">
        <div style="display:table; width:400px;">
            <div id="a" style="height:30px;"></div>
            <div id="b" style="height:30px;"></div>
        </div>
    </body></html>"#,
    );

    let a = harness.layout_rect("#a");
    let b = harness.layout_rect("#b");
    assert!(a.width > 0.0 && a.height > 0.0, "got {a:?}");
    assert!(b.width > 0.0 && b.height > 0.0, "got {b:?}");
    assert_eq!(
        a.x, b.x,
        "run-sharing children should be in the same column"
    );
    assert!(
        b.y >= a.y + a.height,
        "run-sharing children should stack vertically: a={a:?} b={b:?}"
    );
}

/// A real cell terminates the anonymous run: the misplaced children form one
/// cell and the real cell forms another column beside it.
#[test]
fn real_cell_closes_anonymous_run() {
    let harness = harness(
        r#"<html><body style="margin:0">
        <div style="display:table; width:400px;">
            <div id="misplaced" style="height:30px;">A</div>
            <div id="cell" style="display:table-cell; width:100px;">B</div>
        </div>
    </body></html>"#,
    );

    let misplaced = harness.layout_rect("#misplaced");
    let cell = harness.layout_rect("#cell");
    assert!(misplaced.width > 0.0 && misplaced.height > 0.0);
    assert!(cell.width > 0.0 && cell.height > 0.0);
    assert!(
        cell.x >= misplaced.x + misplaced.width,
        "real cell should form its own column: misplaced={misplaced:?} cell={cell:?}"
    );
}

/// Table cells directly under the table (no row) get an anonymous row and
/// lay out side by side.
#[test]
fn cells_directly_under_table_get_anonymous_row() {
    let harness = harness(
        r#"<html><body style="margin:0">
        <div style="display:table; width:400px;">
            <div id="c1" style="display:table-cell; width:200px; height:40px;">A</div>
            <div id="c2" style="display:table-cell; width:200px; height:40px;">B</div>
        </div>
    </body></html>"#,
    );

    let c1 = harness.layout_rect("#c1");
    let c2 = harness.layout_rect("#c2");
    assert!(c1.width > 0.0 && c1.height > 0.0);
    assert!(c2.width > 0.0 && c2.height > 0.0);
    assert_eq!(c1.y, c2.y, "cells in the anonymous row should share a row");
    assert!(
        c2.x >= c1.x + c1.width,
        "cells should lay out side by side: c1={c1:?} c2={c2:?}"
    );
}

/// Bare text directly under a table is wrapped in an anonymous cell and laid
/// out (the table gets a nonzero content height).
#[test]
fn bare_text_under_table_is_laid_out() {
    let harness = harness(
        r#"<html><body style="margin:0">
        <div id="table" style="display:table; width:400px;">hello world</div>
    </body></html>"#,
    );

    let table = harness.layout_rect("#table");
    assert!(
        table.height > 0.0,
        "table with bare text content should have height, got {table:?}"
    );
}

/// Table-internal boxes outside a table (missing parent) are wrapped in an
/// anonymous table: sibling table-cells in a block container lay out side by
/// side as columns of the generated table.
#[test]
fn stray_cells_in_block_container_generate_anonymous_table() {
    let harness = harness(
        r#"<html><body style="margin:0">
        <div style="width:400px;">
            <div id="s1" style="display:table-cell; width:150px; height:40px;">A</div>
            <div id="s2" style="display:table-cell; width:150px; height:40px;">B</div>
        </div>
    </body></html>"#,
    );

    let s1 = harness.layout_rect("#s1");
    let s2 = harness.layout_rect("#s2");
    assert!(s1.width > 0.0 && s1.height > 0.0, "got {s1:?}");
    assert!(s2.width > 0.0 && s2.height > 0.0, "got {s2:?}");
    assert_eq!(s1.y, s2.y, "stray cells should share an anonymous row");
    assert!(
        s2.x >= s1.x + s1.width,
        "stray cells should lay out side by side: s1={s1:?} s2={s2:?}"
    );
}

/// A stray table-row outside a table is likewise wrapped: its cells lay out
/// side by side.
#[test]
fn stray_row_in_block_container_generates_anonymous_table() {
    let harness = harness(
        r#"<html><body style="margin:0">
        <div style="width:400px;">
            <div style="display:table-row;">
                <div id="r1" style="display:table-cell; width:150px; height:40px;">A</div>
                <div id="r2" style="display:table-cell; width:150px; height:40px;">B</div>
            </div>
        </div>
    </body></html>"#,
    );

    let r1 = harness.layout_rect("#r1");
    let r2 = harness.layout_rect("#r2");
    assert!(r1.width > 0.0 && r1.height > 0.0, "got {r1:?}");
    assert!(r2.width > 0.0 && r2.height > 0.0, "got {r2:?}");
    assert_eq!(r1.y, r2.y);
    assert!(
        r2.x >= r1.x + r1.width,
        "cells of a stray row should lay out side by side: r1={r1:?} r2={r2:?}"
    );
}

/// Incremental mutations inside a fixed-up table update geometry and do not
/// leak anonymous nodes.
#[test]
fn incremental_mutations_update_geometry_without_leaking() {
    let mut harness = harness(
        r#"<html><body style="margin:0">
        <div style="display:table; width:400px;">
            <div id="a" style="height:30px;"></div>
            <div id="b" style="height:30px;"></div>
        </div>
    </body></html>"#,
    );

    let a = harness.node("#a");
    let style = blitz_dom::QualName::new(None, blitz_dom::ns!(), blitz_dom::local_name!("style"));

    let node_count_before = harness.base().tree().len();

    for i in 0..10 {
        let height = 30 + 10 * (i % 2);
        harness
            .base_mut()
            .mutate()
            .set_attribute(a, style.clone(), &format!("height:{height}px;"));
        harness.pump();
        let rect = harness.layout_rect("#a");
        assert_eq!(
            rect.height, height as f32,
            "mutation {i} should update the misplaced child's geometry"
        );
    }

    assert_eq!(
        harness.base().tree().len(),
        node_count_before,
        "repeated incremental mutations must not leak nodes"
    );
}

/// Full (non-incremental) reconstructions of tables with fixups must not
/// leak anonymous nodes.
#[test]
fn table_fixup_anonymous_nodes_do_not_leak_across_reconstructions() {
    let mut doc = document(
        r#"<html><body style="margin:0">
        <div style="display:table; width:400px;">
            <div style="height:30px;">misplaced</div>
            <div style="display:table-cell;">cell without row</div>
        </div>
        <div style="width:400px;">
            <div style="display:table-cell;">stray cell</div>
        </div>
    </body></html>"#,
    );

    doc.set_incremental_layout(false);
    doc.resolve(0.0);

    let anon_after_first = doc
        .tree()
        .iter()
        .filter(|(_, node)| node.is_anonymous())
        .count();
    let nodes_after_first = doc.tree().len();

    assert!(
        anon_after_first >= 3,
        "expected anonymous table fixup nodes to be generated, got {anon_after_first}"
    );

    for _ in 0..20 {
        doc.resolve(0.0);
    }

    let anon_after_many = doc
        .tree()
        .iter()
        .filter(|(_, node)| node.is_anonymous())
        .count();

    assert_eq!(
        anon_after_many, anon_after_first,
        "anonymous fixup node count grew across reconstructions"
    );
    assert_eq!(
        doc.tree().len(),
        nodes_after_first,
        "total node count grew across reconstructions"
    );
}
