//! CSS transition events (`transitionrun`, `transitionstart`, `transitionend`,
//! `transitioncancel`) are generated during style resolution as transitions
//! are created, advance through their lifecycle, and complete or get canceled.
//! They are queued on the document and drained via `take_pending_events`.

use blitz_dom::DocumentConfig;
use blitz_html::{HtmlDocument, HtmlProvider};
use blitz_traits::{
    events::DomEventData,
    shell::{ColorScheme, Viewport},
};
use std::sync::Arc;

fn doc(html: &str) -> HtmlDocument {
    let mut doc = HtmlDocument::from_html(
        html,
        DocumentConfig {
            viewport: Some(Viewport::new(400, 400, 1.0, ColorScheme::Light)),
            html_parser_provider: Some(Arc::new(HtmlProvider) as _),
            ..Default::default()
        },
    );
    doc.resolve(0.0);
    // Discard any events generated by the initial resolve.
    let _ = doc.take_pending_events();
    doc
}

fn event_names(doc: &mut HtmlDocument) -> Vec<String> {
    doc.take_pending_events()
        .iter()
        .map(|e| e.name().to_string())
        .collect()
}

/// Set an inline style property and mark the node's ancestors dirty so the
/// incremental style traversal re-cascades it (mirroring what the engine does
/// when style changes during normal operation).
fn set_style(doc: &mut HtmlDocument, node_id: usize, name: &str, value: &str) {
    doc.set_style_property(node_id, name, value);
    doc.get_node(node_id).unwrap().mark_ancestors_dirty();
}

fn transitioning_doc() -> (HtmlDocument, usize) {
    let doc = doc(r#"<html><head><style>
        #box { width: 100px; height: 50px; transition: width 1s linear; }
    </style></head><body style="margin:0">
        <div id="box"></div>
    </body></html>"#);
    let box_id = doc.get_element_by_id("box").expect("#box should exist");
    (doc, box_id)
}

#[test]
fn changing_a_transitioning_property_fires_run_and_start() {
    let (mut doc, box_id) = transitioning_doc();

    // Change the transitioning property: this creates a transition.
    set_style(&mut doc, box_id, "width", "300px");
    doc.resolve(0.0);

    let events = doc.take_pending_events();
    let names: Vec<&str> = events.iter().map(|e| e.name()).collect();

    assert!(
        names.contains(&"transitionrun"),
        "expected a transitionrun event, got {names:?}"
    );
    assert!(
        names.contains(&"transitionstart"),
        "expected a transitionstart event, got {names:?}"
    );

    // The events should target the box element and report the right property.
    let run = events
        .iter()
        .find(|e| e.name() == "transitionrun")
        .unwrap();
    assert_eq!(run.target, box_id);
    let DomEventData::TransitionRun(data) = &run.data else {
        panic!("expected TransitionRun data");
    };
    assert_eq!(data.property_name, "width");
    assert_eq!(data.pseudo_element, "");
}

#[test]
fn completing_a_transition_fires_transitionend() {
    let (mut doc, box_id) = transitioning_doc();

    set_style(&mut doc, box_id, "width", "300px");
    doc.resolve(0.0);
    let _ = doc.take_pending_events();

    // Partway through the 1s transition: no end event yet.
    doc.resolve(0.5);
    let names = event_names(&mut doc);
    assert!(
        !names.contains(&"transitionend".to_string()),
        "transition should not have ended yet, got {names:?}"
    );

    // After the full duration has elapsed: transitionend fires.
    doc.resolve(1.5);
    let events = doc.take_pending_events();
    let names: Vec<&str> = events.iter().map(|e| e.name()).collect();
    assert!(
        names.contains(&"transitionend"),
        "expected a transitionend event, got {names:?}"
    );

    let end = events
        .iter()
        .find(|e| e.name() == "transitionend")
        .unwrap();
    let DomEventData::TransitionEnd(data) = &end.data else {
        panic!("expected TransitionEnd data");
    };
    assert_eq!(data.property_name, "width");
    // `transitionend` reports the full active duration.
    assert!(
        (data.elapsed_time - 1.0).abs() < 1e-3,
        "elapsed_time should be the duration (1.0), got {}",
        data.elapsed_time
    );
}

#[test]
fn canceling_a_transition_fires_transitioncancel() {
    let (mut doc, box_id) = transitioning_doc();

    set_style(&mut doc, box_id, "width", "300px");
    doc.resolve(0.0);
    let _ = doc.take_pending_events();

    // Partway through, remove the transition so the running transition is
    // canceled rather than completing.
    doc.resolve(0.3);
    let _ = doc.take_pending_events();
    set_style(&mut doc, box_id, "transition", "none");
    doc.resolve(0.3);

    let names = event_names(&mut doc);
    assert!(
        names.contains(&"transitioncancel".to_string()),
        "expected a transitioncancel event, got {names:?}"
    );
    assert!(
        !names.contains(&"transitionend".to_string()),
        "a canceled transition should not also end, got {names:?}"
    );
}
