//! Two-way conversions between [`keyboard-types`](https://docs.rs/keyboard-types) v0.7 and v0.8 types.
//!
//! The [`to_08`] module converts v0.7 types to v0.8 types, and the [`to_07`]
//! module converts v0.8 types to v0.7 types.
//!
//! All conversions are lossless except for [`Code`](kt08::Code) variants that
//! only exist in v0.8 (e.g. `KeyboardBacklightToggle`), which map to
//! [`Code::Unidentified`](kt07::Code::Unidentified) when converting to v0.7.

pub use kt07;
pub use kt08;

#[cfg(test)]
mod test_names;
#[cfg(test)]
mod tests;

/// Convert `keyboard-types` v0.7 types to v0.8 types.
pub mod to_08 {
    use kt07 as old;
    use kt08 as new;

    /// Convert a v0.7 [`KeyboardEvent`](old::KeyboardEvent) to a v0.8 [`KeyboardEvent`](new::KeyboardEvent).
    pub fn keyboard_event(event: old::KeyboardEvent) -> new::KeyboardEvent {
        new::KeyboardEvent {
            state: key_state(event.state),
            key: key(event.key),
            code: code(event.code),
            location: location(event.location),
            modifiers: modifiers(event.modifiers),
            repeat: event.repeat,
            is_composing: event.is_composing,
        }
    }

    /// Convert a v0.7 [`CompositionEvent`](old::CompositionEvent) to a v0.8 [`CompositionEvent`](new::CompositionEvent).
    pub fn composition_event(event: old::CompositionEvent) -> new::CompositionEvent {
        new::CompositionEvent {
            state: composition_state(event.state),
            data: event.data,
        }
    }

    /// Convert a v0.7 [`CompositionState`](old::CompositionState) to a v0.8 [`CompositionState`](new::CompositionState).
    pub fn composition_state(state: old::CompositionState) -> new::CompositionState {
        match state {
            old::CompositionState::Start => new::CompositionState::Start,
            old::CompositionState::Update => new::CompositionState::Update,
            old::CompositionState::End => new::CompositionState::End,
        }
    }

    /// Convert a v0.7 [`KeyState`](old::KeyState) to a v0.8 [`KeyState`](new::KeyState).
    pub fn key_state(state: old::KeyState) -> new::KeyState {
        match state {
            old::KeyState::Down => new::KeyState::Down,
            old::KeyState::Up => new::KeyState::Up,
        }
    }

    /// Convert a v0.7 [`Location`](old::Location) to a v0.8 [`Location`](new::Location).
    pub fn location(location: old::Location) -> new::Location {
        match location {
            old::Location::Standard => new::Location::Standard,
            old::Location::Left => new::Location::Left,
            old::Location::Right => new::Location::Right,
            old::Location::Numpad => new::Location::Numpad,
        }
    }

    /// Convert v0.7 [`Modifiers`](old::Modifiers) to v0.8 [`Modifiers`](new::Modifiers).
    pub fn modifiers(modifiers: old::Modifiers) -> new::Modifiers {
        new::Modifiers::from_bits_truncate(modifiers.bits())
    }

    /// Convert a v0.7 [`Key`](old::Key) to a v0.8 [`Key`](new::Key).
    #[allow(deprecated)]
    pub fn key(key: old::Key) -> new::Key {
        match key {
            old::Key::Character(s) => new::Key::Character(s),
            old::Key::Unidentified => new::Key::Named(new::NamedKey::Unidentified),
            old::Key::Alt => new::Key::Named(new::NamedKey::Alt),
            old::Key::AltGraph => new::Key::Named(new::NamedKey::AltGraph),
            old::Key::CapsLock => new::Key::Named(new::NamedKey::CapsLock),
            old::Key::Control => new::Key::Named(new::NamedKey::Control),
            old::Key::Fn => new::Key::Named(new::NamedKey::Fn),
            old::Key::FnLock => new::Key::Named(new::NamedKey::FnLock),
            old::Key::Meta => new::Key::Named(new::NamedKey::Meta),
            old::Key::NumLock => new::Key::Named(new::NamedKey::NumLock),
            old::Key::ScrollLock => new::Key::Named(new::NamedKey::ScrollLock),
            old::Key::Shift => new::Key::Named(new::NamedKey::Shift),
            old::Key::Symbol => new::Key::Named(new::NamedKey::Symbol),
            old::Key::SymbolLock => new::Key::Named(new::NamedKey::SymbolLock),
            old::Key::Hyper => new::Key::Named(new::NamedKey::Hyper),
            old::Key::Super => new::Key::Named(new::NamedKey::Super),
            old::Key::Enter => new::Key::Named(new::NamedKey::Enter),
            old::Key::Tab => new::Key::Named(new::NamedKey::Tab),
            old::Key::ArrowDown => new::Key::Named(new::NamedKey::ArrowDown),
            old::Key::ArrowLeft => new::Key::Named(new::NamedKey::ArrowLeft),
            old::Key::ArrowRight => new::Key::Named(new::NamedKey::ArrowRight),
            old::Key::ArrowUp => new::Key::Named(new::NamedKey::ArrowUp),
            old::Key::End => new::Key::Named(new::NamedKey::End),
            old::Key::Home => new::Key::Named(new::NamedKey::Home),
            old::Key::PageDown => new::Key::Named(new::NamedKey::PageDown),
            old::Key::PageUp => new::Key::Named(new::NamedKey::PageUp),
            old::Key::Backspace => new::Key::Named(new::NamedKey::Backspace),
            old::Key::Clear => new::Key::Named(new::NamedKey::Clear),
            old::Key::Copy => new::Key::Named(new::NamedKey::Copy),
            old::Key::CrSel => new::Key::Named(new::NamedKey::CrSel),
            old::Key::Cut => new::Key::Named(new::NamedKey::Cut),
            old::Key::Delete => new::Key::Named(new::NamedKey::Delete),
            old::Key::EraseEof => new::Key::Named(new::NamedKey::EraseEof),
            old::Key::ExSel => new::Key::Named(new::NamedKey::ExSel),
            old::Key::Insert => new::Key::Named(new::NamedKey::Insert),
            old::Key::Paste => new::Key::Named(new::NamedKey::Paste),
            old::Key::Redo => new::Key::Named(new::NamedKey::Redo),
            old::Key::Undo => new::Key::Named(new::NamedKey::Undo),
            old::Key::Accept => new::Key::Named(new::NamedKey::Accept),
            old::Key::Again => new::Key::Named(new::NamedKey::Again),
            old::Key::Attn => new::Key::Named(new::NamedKey::Attn),
            old::Key::Cancel => new::Key::Named(new::NamedKey::Cancel),
            old::Key::ContextMenu => new::Key::Named(new::NamedKey::ContextMenu),
            old::Key::Escape => new::Key::Named(new::NamedKey::Escape),
            old::Key::Execute => new::Key::Named(new::NamedKey::Execute),
            old::Key::Find => new::Key::Named(new::NamedKey::Find),
            old::Key::Help => new::Key::Named(new::NamedKey::Help),
            old::Key::Pause => new::Key::Named(new::NamedKey::Pause),
            old::Key::Play => new::Key::Named(new::NamedKey::Play),
            old::Key::Props => new::Key::Named(new::NamedKey::Props),
            old::Key::Select => new::Key::Named(new::NamedKey::Select),
            old::Key::ZoomIn => new::Key::Named(new::NamedKey::ZoomIn),
            old::Key::ZoomOut => new::Key::Named(new::NamedKey::ZoomOut),
            old::Key::BrightnessDown => new::Key::Named(new::NamedKey::BrightnessDown),
            old::Key::BrightnessUp => new::Key::Named(new::NamedKey::BrightnessUp),
            old::Key::Eject => new::Key::Named(new::NamedKey::Eject),
            old::Key::LogOff => new::Key::Named(new::NamedKey::LogOff),
            old::Key::Power => new::Key::Named(new::NamedKey::Power),
            old::Key::PowerOff => new::Key::Named(new::NamedKey::PowerOff),
            old::Key::PrintScreen => new::Key::Named(new::NamedKey::PrintScreen),
            old::Key::Hibernate => new::Key::Named(new::NamedKey::Hibernate),
            old::Key::Standby => new::Key::Named(new::NamedKey::Standby),
            old::Key::WakeUp => new::Key::Named(new::NamedKey::WakeUp),
            old::Key::AllCandidates => new::Key::Named(new::NamedKey::AllCandidates),
            old::Key::Alphanumeric => new::Key::Named(new::NamedKey::Alphanumeric),
            old::Key::CodeInput => new::Key::Named(new::NamedKey::CodeInput),
            old::Key::Compose => new::Key::Named(new::NamedKey::Compose),
            old::Key::Convert => new::Key::Named(new::NamedKey::Convert),
            old::Key::Dead => new::Key::Named(new::NamedKey::Dead),
            old::Key::FinalMode => new::Key::Named(new::NamedKey::FinalMode),
            old::Key::GroupFirst => new::Key::Named(new::NamedKey::GroupFirst),
            old::Key::GroupLast => new::Key::Named(new::NamedKey::GroupLast),
            old::Key::GroupNext => new::Key::Named(new::NamedKey::GroupNext),
            old::Key::GroupPrevious => new::Key::Named(new::NamedKey::GroupPrevious),
            old::Key::ModeChange => new::Key::Named(new::NamedKey::ModeChange),
            old::Key::NextCandidate => new::Key::Named(new::NamedKey::NextCandidate),
            old::Key::NonConvert => new::Key::Named(new::NamedKey::NonConvert),
            old::Key::PreviousCandidate => new::Key::Named(new::NamedKey::PreviousCandidate),
            old::Key::Process => new::Key::Named(new::NamedKey::Process),
            old::Key::SingleCandidate => new::Key::Named(new::NamedKey::SingleCandidate),
            old::Key::HangulMode => new::Key::Named(new::NamedKey::HangulMode),
            old::Key::HanjaMode => new::Key::Named(new::NamedKey::HanjaMode),
            old::Key::JunjaMode => new::Key::Named(new::NamedKey::JunjaMode),
            old::Key::Eisu => new::Key::Named(new::NamedKey::Eisu),
            old::Key::Hankaku => new::Key::Named(new::NamedKey::Hankaku),
            old::Key::Hiragana => new::Key::Named(new::NamedKey::Hiragana),
            old::Key::HiraganaKatakana => new::Key::Named(new::NamedKey::HiraganaKatakana),
            old::Key::KanaMode => new::Key::Named(new::NamedKey::KanaMode),
            old::Key::KanjiMode => new::Key::Named(new::NamedKey::KanjiMode),
            old::Key::Katakana => new::Key::Named(new::NamedKey::Katakana),
            old::Key::Romaji => new::Key::Named(new::NamedKey::Romaji),
            old::Key::Zenkaku => new::Key::Named(new::NamedKey::Zenkaku),
            old::Key::ZenkakuHankaku => new::Key::Named(new::NamedKey::ZenkakuHankaku),
            old::Key::Soft1 => new::Key::Named(new::NamedKey::Soft1),
            old::Key::Soft2 => new::Key::Named(new::NamedKey::Soft2),
            old::Key::Soft3 => new::Key::Named(new::NamedKey::Soft3),
            old::Key::Soft4 => new::Key::Named(new::NamedKey::Soft4),
            old::Key::ChannelDown => new::Key::Named(new::NamedKey::ChannelDown),
            old::Key::ChannelUp => new::Key::Named(new::NamedKey::ChannelUp),
            old::Key::Close => new::Key::Named(new::NamedKey::Close),
            old::Key::MailForward => new::Key::Named(new::NamedKey::MailForward),
            old::Key::MailReply => new::Key::Named(new::NamedKey::MailReply),
            old::Key::MailSend => new::Key::Named(new::NamedKey::MailSend),
            old::Key::MediaClose => new::Key::Named(new::NamedKey::MediaClose),
            old::Key::MediaFastForward => new::Key::Named(new::NamedKey::MediaFastForward),
            old::Key::MediaPause => new::Key::Named(new::NamedKey::MediaPause),
            old::Key::MediaPlay => new::Key::Named(new::NamedKey::MediaPlay),
            old::Key::MediaPlayPause => new::Key::Named(new::NamedKey::MediaPlayPause),
            old::Key::MediaRecord => new::Key::Named(new::NamedKey::MediaRecord),
            old::Key::MediaRewind => new::Key::Named(new::NamedKey::MediaRewind),
            old::Key::MediaStop => new::Key::Named(new::NamedKey::MediaStop),
            old::Key::MediaTrackNext => new::Key::Named(new::NamedKey::MediaTrackNext),
            old::Key::MediaTrackPrevious => new::Key::Named(new::NamedKey::MediaTrackPrevious),
            old::Key::New => new::Key::Named(new::NamedKey::New),
            old::Key::Open => new::Key::Named(new::NamedKey::Open),
            old::Key::Print => new::Key::Named(new::NamedKey::Print),
            old::Key::Save => new::Key::Named(new::NamedKey::Save),
            old::Key::SpellCheck => new::Key::Named(new::NamedKey::SpellCheck),
            old::Key::Key11 => new::Key::Named(new::NamedKey::Key11),
            old::Key::Key12 => new::Key::Named(new::NamedKey::Key12),
            old::Key::AudioBalanceLeft => new::Key::Named(new::NamedKey::AudioBalanceLeft),
            old::Key::AudioBalanceRight => new::Key::Named(new::NamedKey::AudioBalanceRight),
            old::Key::AudioBassBoostDown => new::Key::Named(new::NamedKey::AudioBassBoostDown),
            old::Key::AudioBassBoostToggle => new::Key::Named(new::NamedKey::AudioBassBoostToggle),
            old::Key::AudioBassBoostUp => new::Key::Named(new::NamedKey::AudioBassBoostUp),
            old::Key::AudioFaderFront => new::Key::Named(new::NamedKey::AudioFaderFront),
            old::Key::AudioFaderRear => new::Key::Named(new::NamedKey::AudioFaderRear),
            old::Key::AudioSurroundModeNext => {
                new::Key::Named(new::NamedKey::AudioSurroundModeNext)
            }
            old::Key::AudioTrebleDown => new::Key::Named(new::NamedKey::AudioTrebleDown),
            old::Key::AudioTrebleUp => new::Key::Named(new::NamedKey::AudioTrebleUp),
            old::Key::AudioVolumeDown => new::Key::Named(new::NamedKey::AudioVolumeDown),
            old::Key::AudioVolumeUp => new::Key::Named(new::NamedKey::AudioVolumeUp),
            old::Key::AudioVolumeMute => new::Key::Named(new::NamedKey::AudioVolumeMute),
            old::Key::MicrophoneToggle => new::Key::Named(new::NamedKey::MicrophoneToggle),
            old::Key::MicrophoneVolumeDown => new::Key::Named(new::NamedKey::MicrophoneVolumeDown),
            old::Key::MicrophoneVolumeUp => new::Key::Named(new::NamedKey::MicrophoneVolumeUp),
            old::Key::MicrophoneVolumeMute => new::Key::Named(new::NamedKey::MicrophoneVolumeMute),
            old::Key::SpeechCorrectionList => new::Key::Named(new::NamedKey::SpeechCorrectionList),
            old::Key::SpeechInputToggle => new::Key::Named(new::NamedKey::SpeechInputToggle),
            old::Key::LaunchApplication1 => new::Key::Named(new::NamedKey::LaunchApplication1),
            old::Key::LaunchApplication2 => new::Key::Named(new::NamedKey::LaunchApplication2),
            old::Key::LaunchCalendar => new::Key::Named(new::NamedKey::LaunchCalendar),
            old::Key::LaunchContacts => new::Key::Named(new::NamedKey::LaunchContacts),
            old::Key::LaunchMail => new::Key::Named(new::NamedKey::LaunchMail),
            old::Key::LaunchMediaPlayer => new::Key::Named(new::NamedKey::LaunchMediaPlayer),
            old::Key::LaunchMusicPlayer => new::Key::Named(new::NamedKey::LaunchMusicPlayer),
            old::Key::LaunchPhone => new::Key::Named(new::NamedKey::LaunchPhone),
            old::Key::LaunchScreenSaver => new::Key::Named(new::NamedKey::LaunchScreenSaver),
            old::Key::LaunchSpreadsheet => new::Key::Named(new::NamedKey::LaunchSpreadsheet),
            old::Key::LaunchWebBrowser => new::Key::Named(new::NamedKey::LaunchWebBrowser),
            old::Key::LaunchWebCam => new::Key::Named(new::NamedKey::LaunchWebCam),
            old::Key::LaunchWordProcessor => new::Key::Named(new::NamedKey::LaunchWordProcessor),
            old::Key::BrowserBack => new::Key::Named(new::NamedKey::BrowserBack),
            old::Key::BrowserFavorites => new::Key::Named(new::NamedKey::BrowserFavorites),
            old::Key::BrowserForward => new::Key::Named(new::NamedKey::BrowserForward),
            old::Key::BrowserHome => new::Key::Named(new::NamedKey::BrowserHome),
            old::Key::BrowserRefresh => new::Key::Named(new::NamedKey::BrowserRefresh),
            old::Key::BrowserSearch => new::Key::Named(new::NamedKey::BrowserSearch),
            old::Key::BrowserStop => new::Key::Named(new::NamedKey::BrowserStop),
            old::Key::AppSwitch => new::Key::Named(new::NamedKey::AppSwitch),
            old::Key::Call => new::Key::Named(new::NamedKey::Call),
            old::Key::Camera => new::Key::Named(new::NamedKey::Camera),
            old::Key::CameraFocus => new::Key::Named(new::NamedKey::CameraFocus),
            old::Key::EndCall => new::Key::Named(new::NamedKey::EndCall),
            old::Key::GoBack => new::Key::Named(new::NamedKey::GoBack),
            old::Key::GoHome => new::Key::Named(new::NamedKey::GoHome),
            old::Key::HeadsetHook => new::Key::Named(new::NamedKey::HeadsetHook),
            old::Key::LastNumberRedial => new::Key::Named(new::NamedKey::LastNumberRedial),
            old::Key::Notification => new::Key::Named(new::NamedKey::Notification),
            old::Key::MannerMode => new::Key::Named(new::NamedKey::MannerMode),
            old::Key::VoiceDial => new::Key::Named(new::NamedKey::VoiceDial),
            old::Key::TV => new::Key::Named(new::NamedKey::TV),
            old::Key::TV3DMode => new::Key::Named(new::NamedKey::TV3DMode),
            old::Key::TVAntennaCable => new::Key::Named(new::NamedKey::TVAntennaCable),
            old::Key::TVAudioDescription => new::Key::Named(new::NamedKey::TVAudioDescription),
            old::Key::TVAudioDescriptionMixDown => {
                new::Key::Named(new::NamedKey::TVAudioDescriptionMixDown)
            }
            old::Key::TVAudioDescriptionMixUp => {
                new::Key::Named(new::NamedKey::TVAudioDescriptionMixUp)
            }
            old::Key::TVContentsMenu => new::Key::Named(new::NamedKey::TVContentsMenu),
            old::Key::TVDataService => new::Key::Named(new::NamedKey::TVDataService),
            old::Key::TVInput => new::Key::Named(new::NamedKey::TVInput),
            old::Key::TVInputComponent1 => new::Key::Named(new::NamedKey::TVInputComponent1),
            old::Key::TVInputComponent2 => new::Key::Named(new::NamedKey::TVInputComponent2),
            old::Key::TVInputComposite1 => new::Key::Named(new::NamedKey::TVInputComposite1),
            old::Key::TVInputComposite2 => new::Key::Named(new::NamedKey::TVInputComposite2),
            old::Key::TVInputHDMI1 => new::Key::Named(new::NamedKey::TVInputHDMI1),
            old::Key::TVInputHDMI2 => new::Key::Named(new::NamedKey::TVInputHDMI2),
            old::Key::TVInputHDMI3 => new::Key::Named(new::NamedKey::TVInputHDMI3),
            old::Key::TVInputHDMI4 => new::Key::Named(new::NamedKey::TVInputHDMI4),
            old::Key::TVInputVGA1 => new::Key::Named(new::NamedKey::TVInputVGA1),
            old::Key::TVMediaContext => new::Key::Named(new::NamedKey::TVMediaContext),
            old::Key::TVNetwork => new::Key::Named(new::NamedKey::TVNetwork),
            old::Key::TVNumberEntry => new::Key::Named(new::NamedKey::TVNumberEntry),
            old::Key::TVPower => new::Key::Named(new::NamedKey::TVPower),
            old::Key::TVRadioService => new::Key::Named(new::NamedKey::TVRadioService),
            old::Key::TVSatellite => new::Key::Named(new::NamedKey::TVSatellite),
            old::Key::TVSatelliteBS => new::Key::Named(new::NamedKey::TVSatelliteBS),
            old::Key::TVSatelliteCS => new::Key::Named(new::NamedKey::TVSatelliteCS),
            old::Key::TVSatelliteToggle => new::Key::Named(new::NamedKey::TVSatelliteToggle),
            old::Key::TVTerrestrialAnalog => new::Key::Named(new::NamedKey::TVTerrestrialAnalog),
            old::Key::TVTerrestrialDigital => new::Key::Named(new::NamedKey::TVTerrestrialDigital),
            old::Key::TVTimer => new::Key::Named(new::NamedKey::TVTimer),
            old::Key::AVRInput => new::Key::Named(new::NamedKey::AVRInput),
            old::Key::AVRPower => new::Key::Named(new::NamedKey::AVRPower),
            old::Key::ColorF0Red => new::Key::Named(new::NamedKey::ColorF0Red),
            old::Key::ColorF1Green => new::Key::Named(new::NamedKey::ColorF1Green),
            old::Key::ColorF2Yellow => new::Key::Named(new::NamedKey::ColorF2Yellow),
            old::Key::ColorF3Blue => new::Key::Named(new::NamedKey::ColorF3Blue),
            old::Key::ColorF4Grey => new::Key::Named(new::NamedKey::ColorF4Grey),
            old::Key::ColorF5Brown => new::Key::Named(new::NamedKey::ColorF5Brown),
            old::Key::ClosedCaptionToggle => new::Key::Named(new::NamedKey::ClosedCaptionToggle),
            old::Key::Dimmer => new::Key::Named(new::NamedKey::Dimmer),
            old::Key::DisplaySwap => new::Key::Named(new::NamedKey::DisplaySwap),
            old::Key::DVR => new::Key::Named(new::NamedKey::DVR),
            old::Key::Exit => new::Key::Named(new::NamedKey::Exit),
            old::Key::FavoriteClear0 => new::Key::Named(new::NamedKey::FavoriteClear0),
            old::Key::FavoriteClear1 => new::Key::Named(new::NamedKey::FavoriteClear1),
            old::Key::FavoriteClear2 => new::Key::Named(new::NamedKey::FavoriteClear2),
            old::Key::FavoriteClear3 => new::Key::Named(new::NamedKey::FavoriteClear3),
            old::Key::FavoriteRecall0 => new::Key::Named(new::NamedKey::FavoriteRecall0),
            old::Key::FavoriteRecall1 => new::Key::Named(new::NamedKey::FavoriteRecall1),
            old::Key::FavoriteRecall2 => new::Key::Named(new::NamedKey::FavoriteRecall2),
            old::Key::FavoriteRecall3 => new::Key::Named(new::NamedKey::FavoriteRecall3),
            old::Key::FavoriteStore0 => new::Key::Named(new::NamedKey::FavoriteStore0),
            old::Key::FavoriteStore1 => new::Key::Named(new::NamedKey::FavoriteStore1),
            old::Key::FavoriteStore2 => new::Key::Named(new::NamedKey::FavoriteStore2),
            old::Key::FavoriteStore3 => new::Key::Named(new::NamedKey::FavoriteStore3),
            old::Key::Guide => new::Key::Named(new::NamedKey::Guide),
            old::Key::GuideNextDay => new::Key::Named(new::NamedKey::GuideNextDay),
            old::Key::GuidePreviousDay => new::Key::Named(new::NamedKey::GuidePreviousDay),
            old::Key::Info => new::Key::Named(new::NamedKey::Info),
            old::Key::InstantReplay => new::Key::Named(new::NamedKey::InstantReplay),
            old::Key::Link => new::Key::Named(new::NamedKey::Link),
            old::Key::ListProgram => new::Key::Named(new::NamedKey::ListProgram),
            old::Key::LiveContent => new::Key::Named(new::NamedKey::LiveContent),
            old::Key::Lock => new::Key::Named(new::NamedKey::Lock),
            old::Key::MediaApps => new::Key::Named(new::NamedKey::MediaApps),
            old::Key::MediaAudioTrack => new::Key::Named(new::NamedKey::MediaAudioTrack),
            old::Key::MediaLast => new::Key::Named(new::NamedKey::MediaLast),
            old::Key::MediaSkipBackward => new::Key::Named(new::NamedKey::MediaSkipBackward),
            old::Key::MediaSkipForward => new::Key::Named(new::NamedKey::MediaSkipForward),
            old::Key::MediaStepBackward => new::Key::Named(new::NamedKey::MediaStepBackward),
            old::Key::MediaStepForward => new::Key::Named(new::NamedKey::MediaStepForward),
            old::Key::MediaTopMenu => new::Key::Named(new::NamedKey::MediaTopMenu),
            old::Key::NavigateIn => new::Key::Named(new::NamedKey::NavigateIn),
            old::Key::NavigateNext => new::Key::Named(new::NamedKey::NavigateNext),
            old::Key::NavigateOut => new::Key::Named(new::NamedKey::NavigateOut),
            old::Key::NavigatePrevious => new::Key::Named(new::NamedKey::NavigatePrevious),
            old::Key::NextFavoriteChannel => new::Key::Named(new::NamedKey::NextFavoriteChannel),
            old::Key::NextUserProfile => new::Key::Named(new::NamedKey::NextUserProfile),
            old::Key::OnDemand => new::Key::Named(new::NamedKey::OnDemand),
            old::Key::Pairing => new::Key::Named(new::NamedKey::Pairing),
            old::Key::PinPDown => new::Key::Named(new::NamedKey::PinPDown),
            old::Key::PinPMove => new::Key::Named(new::NamedKey::PinPMove),
            old::Key::PinPToggle => new::Key::Named(new::NamedKey::PinPToggle),
            old::Key::PinPUp => new::Key::Named(new::NamedKey::PinPUp),
            old::Key::PlaySpeedDown => new::Key::Named(new::NamedKey::PlaySpeedDown),
            old::Key::PlaySpeedReset => new::Key::Named(new::NamedKey::PlaySpeedReset),
            old::Key::PlaySpeedUp => new::Key::Named(new::NamedKey::PlaySpeedUp),
            old::Key::RandomToggle => new::Key::Named(new::NamedKey::RandomToggle),
            old::Key::RcLowBattery => new::Key::Named(new::NamedKey::RcLowBattery),
            old::Key::RecordSpeedNext => new::Key::Named(new::NamedKey::RecordSpeedNext),
            old::Key::RfBypass => new::Key::Named(new::NamedKey::RfBypass),
            old::Key::ScanChannelsToggle => new::Key::Named(new::NamedKey::ScanChannelsToggle),
            old::Key::ScreenModeNext => new::Key::Named(new::NamedKey::ScreenModeNext),
            old::Key::Settings => new::Key::Named(new::NamedKey::Settings),
            old::Key::SplitScreenToggle => new::Key::Named(new::NamedKey::SplitScreenToggle),
            old::Key::STBInput => new::Key::Named(new::NamedKey::STBInput),
            old::Key::STBPower => new::Key::Named(new::NamedKey::STBPower),
            old::Key::Subtitle => new::Key::Named(new::NamedKey::Subtitle),
            old::Key::Teletext => new::Key::Named(new::NamedKey::Teletext),
            old::Key::VideoModeNext => new::Key::Named(new::NamedKey::VideoModeNext),
            old::Key::Wink => new::Key::Named(new::NamedKey::Wink),
            old::Key::ZoomToggle => new::Key::Named(new::NamedKey::ZoomToggle),
            old::Key::F1 => new::Key::Named(new::NamedKey::F1),
            old::Key::F2 => new::Key::Named(new::NamedKey::F2),
            old::Key::F3 => new::Key::Named(new::NamedKey::F3),
            old::Key::F4 => new::Key::Named(new::NamedKey::F4),
            old::Key::F5 => new::Key::Named(new::NamedKey::F5),
            old::Key::F6 => new::Key::Named(new::NamedKey::F6),
            old::Key::F7 => new::Key::Named(new::NamedKey::F7),
            old::Key::F8 => new::Key::Named(new::NamedKey::F8),
            old::Key::F9 => new::Key::Named(new::NamedKey::F9),
            old::Key::F10 => new::Key::Named(new::NamedKey::F10),
            old::Key::F11 => new::Key::Named(new::NamedKey::F11),
            old::Key::F12 => new::Key::Named(new::NamedKey::F12),
            old::Key::F13 => new::Key::Named(new::NamedKey::F13),
            old::Key::F14 => new::Key::Named(new::NamedKey::F14),
            old::Key::F15 => new::Key::Named(new::NamedKey::F15),
            old::Key::F16 => new::Key::Named(new::NamedKey::F16),
            old::Key::F17 => new::Key::Named(new::NamedKey::F17),
            old::Key::F18 => new::Key::Named(new::NamedKey::F18),
            old::Key::F19 => new::Key::Named(new::NamedKey::F19),
            old::Key::F20 => new::Key::Named(new::NamedKey::F20),
            old::Key::F21 => new::Key::Named(new::NamedKey::F21),
            old::Key::F22 => new::Key::Named(new::NamedKey::F22),
            old::Key::F23 => new::Key::Named(new::NamedKey::F23),
            old::Key::F24 => new::Key::Named(new::NamedKey::F24),
            old::Key::F25 => new::Key::Named(new::NamedKey::F25),
            old::Key::F26 => new::Key::Named(new::NamedKey::F26),
            old::Key::F27 => new::Key::Named(new::NamedKey::F27),
            old::Key::F28 => new::Key::Named(new::NamedKey::F28),
            old::Key::F29 => new::Key::Named(new::NamedKey::F29),
            old::Key::F30 => new::Key::Named(new::NamedKey::F30),
            old::Key::F31 => new::Key::Named(new::NamedKey::F31),
            old::Key::F32 => new::Key::Named(new::NamedKey::F32),
            old::Key::F33 => new::Key::Named(new::NamedKey::F33),
            old::Key::F34 => new::Key::Named(new::NamedKey::F34),
            old::Key::F35 => new::Key::Named(new::NamedKey::F35),
            // `Key` is #[non_exhaustive]
            _ => new::Key::Named(new::NamedKey::Unidentified),
        }
    }

    /// Convert a v0.7 [`Code`](old::Code) to a v0.8 [`Code`](new::Code).
    #[allow(deprecated)]
    pub fn code(code: old::Code) -> new::Code {
        match code {
            old::Code::Backquote => new::Code::Backquote,
            old::Code::Backslash => new::Code::Backslash,
            old::Code::BracketLeft => new::Code::BracketLeft,
            old::Code::BracketRight => new::Code::BracketRight,
            old::Code::Comma => new::Code::Comma,
            old::Code::Digit0 => new::Code::Digit0,
            old::Code::Digit1 => new::Code::Digit1,
            old::Code::Digit2 => new::Code::Digit2,
            old::Code::Digit3 => new::Code::Digit3,
            old::Code::Digit4 => new::Code::Digit4,
            old::Code::Digit5 => new::Code::Digit5,
            old::Code::Digit6 => new::Code::Digit6,
            old::Code::Digit7 => new::Code::Digit7,
            old::Code::Digit8 => new::Code::Digit8,
            old::Code::Digit9 => new::Code::Digit9,
            old::Code::Equal => new::Code::Equal,
            old::Code::IntlBackslash => new::Code::IntlBackslash,
            old::Code::IntlRo => new::Code::IntlRo,
            old::Code::IntlYen => new::Code::IntlYen,
            old::Code::KeyA => new::Code::KeyA,
            old::Code::KeyB => new::Code::KeyB,
            old::Code::KeyC => new::Code::KeyC,
            old::Code::KeyD => new::Code::KeyD,
            old::Code::KeyE => new::Code::KeyE,
            old::Code::KeyF => new::Code::KeyF,
            old::Code::KeyG => new::Code::KeyG,
            old::Code::KeyH => new::Code::KeyH,
            old::Code::KeyI => new::Code::KeyI,
            old::Code::KeyJ => new::Code::KeyJ,
            old::Code::KeyK => new::Code::KeyK,
            old::Code::KeyL => new::Code::KeyL,
            old::Code::KeyM => new::Code::KeyM,
            old::Code::KeyN => new::Code::KeyN,
            old::Code::KeyO => new::Code::KeyO,
            old::Code::KeyP => new::Code::KeyP,
            old::Code::KeyQ => new::Code::KeyQ,
            old::Code::KeyR => new::Code::KeyR,
            old::Code::KeyS => new::Code::KeyS,
            old::Code::KeyT => new::Code::KeyT,
            old::Code::KeyU => new::Code::KeyU,
            old::Code::KeyV => new::Code::KeyV,
            old::Code::KeyW => new::Code::KeyW,
            old::Code::KeyX => new::Code::KeyX,
            old::Code::KeyY => new::Code::KeyY,
            old::Code::KeyZ => new::Code::KeyZ,
            old::Code::Minus => new::Code::Minus,
            old::Code::Period => new::Code::Period,
            old::Code::Quote => new::Code::Quote,
            old::Code::Semicolon => new::Code::Semicolon,
            old::Code::Slash => new::Code::Slash,
            old::Code::AltLeft => new::Code::AltLeft,
            old::Code::AltRight => new::Code::AltRight,
            old::Code::Backspace => new::Code::Backspace,
            old::Code::CapsLock => new::Code::CapsLock,
            old::Code::ContextMenu => new::Code::ContextMenu,
            old::Code::ControlLeft => new::Code::ControlLeft,
            old::Code::ControlRight => new::Code::ControlRight,
            old::Code::Enter => new::Code::Enter,
            old::Code::MetaLeft => new::Code::MetaLeft,
            old::Code::MetaRight => new::Code::MetaRight,
            old::Code::ShiftLeft => new::Code::ShiftLeft,
            old::Code::ShiftRight => new::Code::ShiftRight,
            old::Code::Space => new::Code::Space,
            old::Code::Tab => new::Code::Tab,
            old::Code::Convert => new::Code::Convert,
            old::Code::KanaMode => new::Code::KanaMode,
            old::Code::Lang1 => new::Code::Lang1,
            old::Code::Lang2 => new::Code::Lang2,
            old::Code::Lang3 => new::Code::Lang3,
            old::Code::Lang4 => new::Code::Lang4,
            old::Code::Lang5 => new::Code::Lang5,
            old::Code::NonConvert => new::Code::NonConvert,
            old::Code::Delete => new::Code::Delete,
            old::Code::End => new::Code::End,
            old::Code::Help => new::Code::Help,
            old::Code::Home => new::Code::Home,
            old::Code::Insert => new::Code::Insert,
            old::Code::PageDown => new::Code::PageDown,
            old::Code::PageUp => new::Code::PageUp,
            old::Code::ArrowDown => new::Code::ArrowDown,
            old::Code::ArrowLeft => new::Code::ArrowLeft,
            old::Code::ArrowRight => new::Code::ArrowRight,
            old::Code::ArrowUp => new::Code::ArrowUp,
            old::Code::NumLock => new::Code::NumLock,
            old::Code::Numpad0 => new::Code::Numpad0,
            old::Code::Numpad1 => new::Code::Numpad1,
            old::Code::Numpad2 => new::Code::Numpad2,
            old::Code::Numpad3 => new::Code::Numpad3,
            old::Code::Numpad4 => new::Code::Numpad4,
            old::Code::Numpad5 => new::Code::Numpad5,
            old::Code::Numpad6 => new::Code::Numpad6,
            old::Code::Numpad7 => new::Code::Numpad7,
            old::Code::Numpad8 => new::Code::Numpad8,
            old::Code::Numpad9 => new::Code::Numpad9,
            old::Code::NumpadAdd => new::Code::NumpadAdd,
            old::Code::NumpadBackspace => new::Code::NumpadBackspace,
            old::Code::NumpadClear => new::Code::NumpadClear,
            old::Code::NumpadClearEntry => new::Code::NumpadClearEntry,
            old::Code::NumpadComma => new::Code::NumpadComma,
            old::Code::NumpadDecimal => new::Code::NumpadDecimal,
            old::Code::NumpadDivide => new::Code::NumpadDivide,
            old::Code::NumpadEnter => new::Code::NumpadEnter,
            old::Code::NumpadEqual => new::Code::NumpadEqual,
            old::Code::NumpadHash => new::Code::NumpadHash,
            old::Code::NumpadMemoryAdd => new::Code::NumpadMemoryAdd,
            old::Code::NumpadMemoryClear => new::Code::NumpadMemoryClear,
            old::Code::NumpadMemoryRecall => new::Code::NumpadMemoryRecall,
            old::Code::NumpadMemoryStore => new::Code::NumpadMemoryStore,
            old::Code::NumpadMemorySubtract => new::Code::NumpadMemorySubtract,
            old::Code::NumpadMultiply => new::Code::NumpadMultiply,
            old::Code::NumpadParenLeft => new::Code::NumpadParenLeft,
            old::Code::NumpadParenRight => new::Code::NumpadParenRight,
            old::Code::NumpadStar => new::Code::NumpadStar,
            old::Code::NumpadSubtract => new::Code::NumpadSubtract,
            old::Code::Escape => new::Code::Escape,
            old::Code::Fn => new::Code::Fn,
            old::Code::FnLock => new::Code::FnLock,
            old::Code::PrintScreen => new::Code::PrintScreen,
            old::Code::ScrollLock => new::Code::ScrollLock,
            old::Code::Pause => new::Code::Pause,
            old::Code::BrowserBack => new::Code::BrowserBack,
            old::Code::BrowserFavorites => new::Code::BrowserFavorites,
            old::Code::BrowserForward => new::Code::BrowserForward,
            old::Code::BrowserHome => new::Code::BrowserHome,
            old::Code::BrowserRefresh => new::Code::BrowserRefresh,
            old::Code::BrowserSearch => new::Code::BrowserSearch,
            old::Code::BrowserStop => new::Code::BrowserStop,
            old::Code::Eject => new::Code::Eject,
            old::Code::LaunchApp1 => new::Code::LaunchApp1,
            old::Code::LaunchApp2 => new::Code::LaunchApp2,
            old::Code::LaunchMail => new::Code::LaunchMail,
            old::Code::MediaPlayPause => new::Code::MediaPlayPause,
            old::Code::MediaSelect => new::Code::MediaSelect,
            old::Code::MediaStop => new::Code::MediaStop,
            old::Code::MediaTrackNext => new::Code::MediaTrackNext,
            old::Code::MediaTrackPrevious => new::Code::MediaTrackPrevious,
            old::Code::Power => new::Code::Power,
            old::Code::Sleep => new::Code::Sleep,
            old::Code::AudioVolumeDown => new::Code::AudioVolumeDown,
            old::Code::AudioVolumeMute => new::Code::AudioVolumeMute,
            old::Code::AudioVolumeUp => new::Code::AudioVolumeUp,
            old::Code::WakeUp => new::Code::WakeUp,
            old::Code::Hyper => new::Code::Hyper,
            old::Code::Super => new::Code::Super,
            old::Code::Turbo => new::Code::Turbo,
            old::Code::Abort => new::Code::Abort,
            old::Code::Resume => new::Code::Resume,
            old::Code::Suspend => new::Code::Suspend,
            old::Code::Again => new::Code::Again,
            old::Code::Copy => new::Code::Copy,
            old::Code::Cut => new::Code::Cut,
            old::Code::Find => new::Code::Find,
            old::Code::Open => new::Code::Open,
            old::Code::Paste => new::Code::Paste,
            old::Code::Props => new::Code::Props,
            old::Code::Select => new::Code::Select,
            old::Code::Undo => new::Code::Undo,
            old::Code::Hiragana => new::Code::Hiragana,
            old::Code::Katakana => new::Code::Katakana,
            old::Code::Unidentified => new::Code::Unidentified,
            old::Code::F1 => new::Code::F1,
            old::Code::F2 => new::Code::F2,
            old::Code::F3 => new::Code::F3,
            old::Code::F4 => new::Code::F4,
            old::Code::F5 => new::Code::F5,
            old::Code::F6 => new::Code::F6,
            old::Code::F7 => new::Code::F7,
            old::Code::F8 => new::Code::F8,
            old::Code::F9 => new::Code::F9,
            old::Code::F10 => new::Code::F10,
            old::Code::F11 => new::Code::F11,
            old::Code::F12 => new::Code::F12,
            old::Code::F13 => new::Code::F13,
            old::Code::F14 => new::Code::F14,
            old::Code::F15 => new::Code::F15,
            old::Code::F16 => new::Code::F16,
            old::Code::F17 => new::Code::F17,
            old::Code::F18 => new::Code::F18,
            old::Code::F19 => new::Code::F19,
            old::Code::F20 => new::Code::F20,
            old::Code::F21 => new::Code::F21,
            old::Code::F22 => new::Code::F22,
            old::Code::F23 => new::Code::F23,
            old::Code::F24 => new::Code::F24,
            old::Code::F25 => new::Code::F25,
            old::Code::F26 => new::Code::F26,
            old::Code::F27 => new::Code::F27,
            old::Code::F28 => new::Code::F28,
            old::Code::F29 => new::Code::F29,
            old::Code::F30 => new::Code::F30,
            old::Code::F31 => new::Code::F31,
            old::Code::F32 => new::Code::F32,
            old::Code::F33 => new::Code::F33,
            old::Code::F34 => new::Code::F34,
            old::Code::F35 => new::Code::F35,
            old::Code::BrightnessDown => new::Code::BrightnessDown,
            old::Code::BrightnessUp => new::Code::BrightnessUp,
            old::Code::DisplayToggleIntExt => new::Code::DisplayToggleIntExt,
            old::Code::KeyboardLayoutSelect => new::Code::KeyboardLayoutSelect,
            old::Code::LaunchAssistant => new::Code::LaunchAssistant,
            old::Code::LaunchControlPanel => new::Code::LaunchControlPanel,
            old::Code::LaunchScreenSaver => new::Code::LaunchScreenSaver,
            old::Code::MailForward => new::Code::MailForward,
            old::Code::MailReply => new::Code::MailReply,
            old::Code::MailSend => new::Code::MailSend,
            old::Code::MediaFastForward => new::Code::MediaFastForward,
            old::Code::MediaPause => new::Code::MediaPause,
            old::Code::MediaPlay => new::Code::MediaPlay,
            old::Code::MediaRecord => new::Code::MediaRecord,
            old::Code::MediaRewind => new::Code::MediaRewind,
            old::Code::MicrophoneMuteToggle => new::Code::MicrophoneMuteToggle,
            old::Code::PrivacyScreenToggle => new::Code::PrivacyScreenToggle,
            old::Code::SelectTask => new::Code::SelectTask,
            old::Code::ShowAllWindows => new::Code::ShowAllWindows,
            old::Code::ZoomToggle => new::Code::ZoomToggle,
            // `Code` is #[non_exhaustive]
            _ => new::Code::Unidentified,
        }
    }
}

/// Convert `keyboard-types` v0.8 types to v0.7 types.
pub mod to_07 {
    use kt07 as new;
    use kt08 as old;

    /// Convert a v0.8 [`KeyboardEvent`](old::KeyboardEvent) to a v0.7 [`KeyboardEvent`](new::KeyboardEvent).
    pub fn keyboard_event(event: old::KeyboardEvent) -> new::KeyboardEvent {
        new::KeyboardEvent {
            state: key_state(event.state),
            key: key(event.key),
            code: code(event.code),
            location: location(event.location),
            modifiers: modifiers(event.modifiers),
            repeat: event.repeat,
            is_composing: event.is_composing,
        }
    }

    /// Convert a v0.8 [`CompositionEvent`](old::CompositionEvent) to a v0.7 [`CompositionEvent`](new::CompositionEvent).
    pub fn composition_event(event: old::CompositionEvent) -> new::CompositionEvent {
        new::CompositionEvent {
            state: composition_state(event.state),
            data: event.data,
        }
    }

    /// Convert a v0.8 [`CompositionState`](old::CompositionState) to a v0.7 [`CompositionState`](new::CompositionState).
    pub fn composition_state(state: old::CompositionState) -> new::CompositionState {
        match state {
            old::CompositionState::Start => new::CompositionState::Start,
            old::CompositionState::Update => new::CompositionState::Update,
            old::CompositionState::End => new::CompositionState::End,
        }
    }

    /// Convert a v0.8 [`KeyState`](old::KeyState) to a v0.7 [`KeyState`](new::KeyState).
    pub fn key_state(state: old::KeyState) -> new::KeyState {
        match state {
            old::KeyState::Down => new::KeyState::Down,
            old::KeyState::Up => new::KeyState::Up,
        }
    }

    /// Convert a v0.8 [`Location`](old::Location) to a v0.7 [`Location`](new::Location).
    pub fn location(location: old::Location) -> new::Location {
        match location {
            old::Location::Standard => new::Location::Standard,
            old::Location::Left => new::Location::Left,
            old::Location::Right => new::Location::Right,
            old::Location::Numpad => new::Location::Numpad,
        }
    }

    /// Convert v0.8 [`Modifiers`](old::Modifiers) to v0.7 [`Modifiers`](new::Modifiers).
    pub fn modifiers(modifiers: old::Modifiers) -> new::Modifiers {
        new::Modifiers::from_bits_truncate(modifiers.bits())
    }

    /// Convert a v0.8 [`Key`](old::Key) to a v0.7 [`Key`](new::Key).
    #[allow(deprecated)]
    pub fn key(key: old::Key) -> new::Key {
        match key {
            old::Key::Character(s) => new::Key::Character(s),
            old::Key::Named(named) => named_key(named),
        }
    }

    /// Convert a v0.8 [`NamedKey`](old::NamedKey) to a v0.7 [`Key`](new::Key).
    #[allow(deprecated)]
    pub fn named_key(key: old::NamedKey) -> new::Key {
        match key {
            old::NamedKey::Unidentified => new::Key::Unidentified,
            old::NamedKey::Alt => new::Key::Alt,
            old::NamedKey::AltGraph => new::Key::AltGraph,
            old::NamedKey::CapsLock => new::Key::CapsLock,
            old::NamedKey::Control => new::Key::Control,
            old::NamedKey::Fn => new::Key::Fn,
            old::NamedKey::FnLock => new::Key::FnLock,
            old::NamedKey::Meta => new::Key::Meta,
            old::NamedKey::NumLock => new::Key::NumLock,
            old::NamedKey::ScrollLock => new::Key::ScrollLock,
            old::NamedKey::Shift => new::Key::Shift,
            old::NamedKey::Symbol => new::Key::Symbol,
            old::NamedKey::SymbolLock => new::Key::SymbolLock,
            old::NamedKey::Hyper => new::Key::Hyper,
            old::NamedKey::Super => new::Key::Super,
            old::NamedKey::Enter => new::Key::Enter,
            old::NamedKey::Tab => new::Key::Tab,
            old::NamedKey::ArrowDown => new::Key::ArrowDown,
            old::NamedKey::ArrowLeft => new::Key::ArrowLeft,
            old::NamedKey::ArrowRight => new::Key::ArrowRight,
            old::NamedKey::ArrowUp => new::Key::ArrowUp,
            old::NamedKey::End => new::Key::End,
            old::NamedKey::Home => new::Key::Home,
            old::NamedKey::PageDown => new::Key::PageDown,
            old::NamedKey::PageUp => new::Key::PageUp,
            old::NamedKey::Backspace => new::Key::Backspace,
            old::NamedKey::Clear => new::Key::Clear,
            old::NamedKey::Copy => new::Key::Copy,
            old::NamedKey::CrSel => new::Key::CrSel,
            old::NamedKey::Cut => new::Key::Cut,
            old::NamedKey::Delete => new::Key::Delete,
            old::NamedKey::EraseEof => new::Key::EraseEof,
            old::NamedKey::ExSel => new::Key::ExSel,
            old::NamedKey::Insert => new::Key::Insert,
            old::NamedKey::Paste => new::Key::Paste,
            old::NamedKey::Redo => new::Key::Redo,
            old::NamedKey::Undo => new::Key::Undo,
            old::NamedKey::Accept => new::Key::Accept,
            old::NamedKey::Again => new::Key::Again,
            old::NamedKey::Attn => new::Key::Attn,
            old::NamedKey::Cancel => new::Key::Cancel,
            old::NamedKey::ContextMenu => new::Key::ContextMenu,
            old::NamedKey::Escape => new::Key::Escape,
            old::NamedKey::Execute => new::Key::Execute,
            old::NamedKey::Find => new::Key::Find,
            old::NamedKey::Help => new::Key::Help,
            old::NamedKey::Pause => new::Key::Pause,
            old::NamedKey::Play => new::Key::Play,
            old::NamedKey::Props => new::Key::Props,
            old::NamedKey::Select => new::Key::Select,
            old::NamedKey::ZoomIn => new::Key::ZoomIn,
            old::NamedKey::ZoomOut => new::Key::ZoomOut,
            old::NamedKey::BrightnessDown => new::Key::BrightnessDown,
            old::NamedKey::BrightnessUp => new::Key::BrightnessUp,
            old::NamedKey::Eject => new::Key::Eject,
            old::NamedKey::LogOff => new::Key::LogOff,
            old::NamedKey::Power => new::Key::Power,
            old::NamedKey::PowerOff => new::Key::PowerOff,
            old::NamedKey::PrintScreen => new::Key::PrintScreen,
            old::NamedKey::Hibernate => new::Key::Hibernate,
            old::NamedKey::Standby => new::Key::Standby,
            old::NamedKey::WakeUp => new::Key::WakeUp,
            old::NamedKey::AllCandidates => new::Key::AllCandidates,
            old::NamedKey::Alphanumeric => new::Key::Alphanumeric,
            old::NamedKey::CodeInput => new::Key::CodeInput,
            old::NamedKey::Compose => new::Key::Compose,
            old::NamedKey::Convert => new::Key::Convert,
            old::NamedKey::Dead => new::Key::Dead,
            old::NamedKey::FinalMode => new::Key::FinalMode,
            old::NamedKey::GroupFirst => new::Key::GroupFirst,
            old::NamedKey::GroupLast => new::Key::GroupLast,
            old::NamedKey::GroupNext => new::Key::GroupNext,
            old::NamedKey::GroupPrevious => new::Key::GroupPrevious,
            old::NamedKey::ModeChange => new::Key::ModeChange,
            old::NamedKey::NextCandidate => new::Key::NextCandidate,
            old::NamedKey::NonConvert => new::Key::NonConvert,
            old::NamedKey::PreviousCandidate => new::Key::PreviousCandidate,
            old::NamedKey::Process => new::Key::Process,
            old::NamedKey::SingleCandidate => new::Key::SingleCandidate,
            old::NamedKey::HangulMode => new::Key::HangulMode,
            old::NamedKey::HanjaMode => new::Key::HanjaMode,
            old::NamedKey::JunjaMode => new::Key::JunjaMode,
            old::NamedKey::Eisu => new::Key::Eisu,
            old::NamedKey::Hankaku => new::Key::Hankaku,
            old::NamedKey::Hiragana => new::Key::Hiragana,
            old::NamedKey::HiraganaKatakana => new::Key::HiraganaKatakana,
            old::NamedKey::KanaMode => new::Key::KanaMode,
            old::NamedKey::KanjiMode => new::Key::KanjiMode,
            old::NamedKey::Katakana => new::Key::Katakana,
            old::NamedKey::Romaji => new::Key::Romaji,
            old::NamedKey::Zenkaku => new::Key::Zenkaku,
            old::NamedKey::ZenkakuHankaku => new::Key::ZenkakuHankaku,
            old::NamedKey::Soft1 => new::Key::Soft1,
            old::NamedKey::Soft2 => new::Key::Soft2,
            old::NamedKey::Soft3 => new::Key::Soft3,
            old::NamedKey::Soft4 => new::Key::Soft4,
            old::NamedKey::ChannelDown => new::Key::ChannelDown,
            old::NamedKey::ChannelUp => new::Key::ChannelUp,
            old::NamedKey::Close => new::Key::Close,
            old::NamedKey::MailForward => new::Key::MailForward,
            old::NamedKey::MailReply => new::Key::MailReply,
            old::NamedKey::MailSend => new::Key::MailSend,
            old::NamedKey::MediaClose => new::Key::MediaClose,
            old::NamedKey::MediaFastForward => new::Key::MediaFastForward,
            old::NamedKey::MediaPause => new::Key::MediaPause,
            old::NamedKey::MediaPlay => new::Key::MediaPlay,
            old::NamedKey::MediaPlayPause => new::Key::MediaPlayPause,
            old::NamedKey::MediaRecord => new::Key::MediaRecord,
            old::NamedKey::MediaRewind => new::Key::MediaRewind,
            old::NamedKey::MediaStop => new::Key::MediaStop,
            old::NamedKey::MediaTrackNext => new::Key::MediaTrackNext,
            old::NamedKey::MediaTrackPrevious => new::Key::MediaTrackPrevious,
            old::NamedKey::New => new::Key::New,
            old::NamedKey::Open => new::Key::Open,
            old::NamedKey::Print => new::Key::Print,
            old::NamedKey::Save => new::Key::Save,
            old::NamedKey::SpellCheck => new::Key::SpellCheck,
            old::NamedKey::Key11 => new::Key::Key11,
            old::NamedKey::Key12 => new::Key::Key12,
            old::NamedKey::AudioBalanceLeft => new::Key::AudioBalanceLeft,
            old::NamedKey::AudioBalanceRight => new::Key::AudioBalanceRight,
            old::NamedKey::AudioBassBoostDown => new::Key::AudioBassBoostDown,
            old::NamedKey::AudioBassBoostToggle => new::Key::AudioBassBoostToggle,
            old::NamedKey::AudioBassBoostUp => new::Key::AudioBassBoostUp,
            old::NamedKey::AudioFaderFront => new::Key::AudioFaderFront,
            old::NamedKey::AudioFaderRear => new::Key::AudioFaderRear,
            old::NamedKey::AudioSurroundModeNext => new::Key::AudioSurroundModeNext,
            old::NamedKey::AudioTrebleDown => new::Key::AudioTrebleDown,
            old::NamedKey::AudioTrebleUp => new::Key::AudioTrebleUp,
            old::NamedKey::AudioVolumeDown => new::Key::AudioVolumeDown,
            old::NamedKey::AudioVolumeUp => new::Key::AudioVolumeUp,
            old::NamedKey::AudioVolumeMute => new::Key::AudioVolumeMute,
            old::NamedKey::MicrophoneToggle => new::Key::MicrophoneToggle,
            old::NamedKey::MicrophoneVolumeDown => new::Key::MicrophoneVolumeDown,
            old::NamedKey::MicrophoneVolumeUp => new::Key::MicrophoneVolumeUp,
            old::NamedKey::MicrophoneVolumeMute => new::Key::MicrophoneVolumeMute,
            old::NamedKey::SpeechCorrectionList => new::Key::SpeechCorrectionList,
            old::NamedKey::SpeechInputToggle => new::Key::SpeechInputToggle,
            old::NamedKey::LaunchApplication1 => new::Key::LaunchApplication1,
            old::NamedKey::LaunchApplication2 => new::Key::LaunchApplication2,
            old::NamedKey::LaunchCalendar => new::Key::LaunchCalendar,
            old::NamedKey::LaunchContacts => new::Key::LaunchContacts,
            old::NamedKey::LaunchMail => new::Key::LaunchMail,
            old::NamedKey::LaunchMediaPlayer => new::Key::LaunchMediaPlayer,
            old::NamedKey::LaunchMusicPlayer => new::Key::LaunchMusicPlayer,
            old::NamedKey::LaunchPhone => new::Key::LaunchPhone,
            old::NamedKey::LaunchScreenSaver => new::Key::LaunchScreenSaver,
            old::NamedKey::LaunchSpreadsheet => new::Key::LaunchSpreadsheet,
            old::NamedKey::LaunchWebBrowser => new::Key::LaunchWebBrowser,
            old::NamedKey::LaunchWebCam => new::Key::LaunchWebCam,
            old::NamedKey::LaunchWordProcessor => new::Key::LaunchWordProcessor,
            old::NamedKey::BrowserBack => new::Key::BrowserBack,
            old::NamedKey::BrowserFavorites => new::Key::BrowserFavorites,
            old::NamedKey::BrowserForward => new::Key::BrowserForward,
            old::NamedKey::BrowserHome => new::Key::BrowserHome,
            old::NamedKey::BrowserRefresh => new::Key::BrowserRefresh,
            old::NamedKey::BrowserSearch => new::Key::BrowserSearch,
            old::NamedKey::BrowserStop => new::Key::BrowserStop,
            old::NamedKey::AppSwitch => new::Key::AppSwitch,
            old::NamedKey::Call => new::Key::Call,
            old::NamedKey::Camera => new::Key::Camera,
            old::NamedKey::CameraFocus => new::Key::CameraFocus,
            old::NamedKey::EndCall => new::Key::EndCall,
            old::NamedKey::GoBack => new::Key::GoBack,
            old::NamedKey::GoHome => new::Key::GoHome,
            old::NamedKey::HeadsetHook => new::Key::HeadsetHook,
            old::NamedKey::LastNumberRedial => new::Key::LastNumberRedial,
            old::NamedKey::Notification => new::Key::Notification,
            old::NamedKey::MannerMode => new::Key::MannerMode,
            old::NamedKey::VoiceDial => new::Key::VoiceDial,
            old::NamedKey::TV => new::Key::TV,
            old::NamedKey::TV3DMode => new::Key::TV3DMode,
            old::NamedKey::TVAntennaCable => new::Key::TVAntennaCable,
            old::NamedKey::TVAudioDescription => new::Key::TVAudioDescription,
            old::NamedKey::TVAudioDescriptionMixDown => new::Key::TVAudioDescriptionMixDown,
            old::NamedKey::TVAudioDescriptionMixUp => new::Key::TVAudioDescriptionMixUp,
            old::NamedKey::TVContentsMenu => new::Key::TVContentsMenu,
            old::NamedKey::TVDataService => new::Key::TVDataService,
            old::NamedKey::TVInput => new::Key::TVInput,
            old::NamedKey::TVInputComponent1 => new::Key::TVInputComponent1,
            old::NamedKey::TVInputComponent2 => new::Key::TVInputComponent2,
            old::NamedKey::TVInputComposite1 => new::Key::TVInputComposite1,
            old::NamedKey::TVInputComposite2 => new::Key::TVInputComposite2,
            old::NamedKey::TVInputHDMI1 => new::Key::TVInputHDMI1,
            old::NamedKey::TVInputHDMI2 => new::Key::TVInputHDMI2,
            old::NamedKey::TVInputHDMI3 => new::Key::TVInputHDMI3,
            old::NamedKey::TVInputHDMI4 => new::Key::TVInputHDMI4,
            old::NamedKey::TVInputVGA1 => new::Key::TVInputVGA1,
            old::NamedKey::TVMediaContext => new::Key::TVMediaContext,
            old::NamedKey::TVNetwork => new::Key::TVNetwork,
            old::NamedKey::TVNumberEntry => new::Key::TVNumberEntry,
            old::NamedKey::TVPower => new::Key::TVPower,
            old::NamedKey::TVRadioService => new::Key::TVRadioService,
            old::NamedKey::TVSatellite => new::Key::TVSatellite,
            old::NamedKey::TVSatelliteBS => new::Key::TVSatelliteBS,
            old::NamedKey::TVSatelliteCS => new::Key::TVSatelliteCS,
            old::NamedKey::TVSatelliteToggle => new::Key::TVSatelliteToggle,
            old::NamedKey::TVTerrestrialAnalog => new::Key::TVTerrestrialAnalog,
            old::NamedKey::TVTerrestrialDigital => new::Key::TVTerrestrialDigital,
            old::NamedKey::TVTimer => new::Key::TVTimer,
            old::NamedKey::AVRInput => new::Key::AVRInput,
            old::NamedKey::AVRPower => new::Key::AVRPower,
            old::NamedKey::ColorF0Red => new::Key::ColorF0Red,
            old::NamedKey::ColorF1Green => new::Key::ColorF1Green,
            old::NamedKey::ColorF2Yellow => new::Key::ColorF2Yellow,
            old::NamedKey::ColorF3Blue => new::Key::ColorF3Blue,
            old::NamedKey::ColorF4Grey => new::Key::ColorF4Grey,
            old::NamedKey::ColorF5Brown => new::Key::ColorF5Brown,
            old::NamedKey::ClosedCaptionToggle => new::Key::ClosedCaptionToggle,
            old::NamedKey::Dimmer => new::Key::Dimmer,
            old::NamedKey::DisplaySwap => new::Key::DisplaySwap,
            old::NamedKey::DVR => new::Key::DVR,
            old::NamedKey::Exit => new::Key::Exit,
            old::NamedKey::FavoriteClear0 => new::Key::FavoriteClear0,
            old::NamedKey::FavoriteClear1 => new::Key::FavoriteClear1,
            old::NamedKey::FavoriteClear2 => new::Key::FavoriteClear2,
            old::NamedKey::FavoriteClear3 => new::Key::FavoriteClear3,
            old::NamedKey::FavoriteRecall0 => new::Key::FavoriteRecall0,
            old::NamedKey::FavoriteRecall1 => new::Key::FavoriteRecall1,
            old::NamedKey::FavoriteRecall2 => new::Key::FavoriteRecall2,
            old::NamedKey::FavoriteRecall3 => new::Key::FavoriteRecall3,
            old::NamedKey::FavoriteStore0 => new::Key::FavoriteStore0,
            old::NamedKey::FavoriteStore1 => new::Key::FavoriteStore1,
            old::NamedKey::FavoriteStore2 => new::Key::FavoriteStore2,
            old::NamedKey::FavoriteStore3 => new::Key::FavoriteStore3,
            old::NamedKey::Guide => new::Key::Guide,
            old::NamedKey::GuideNextDay => new::Key::GuideNextDay,
            old::NamedKey::GuidePreviousDay => new::Key::GuidePreviousDay,
            old::NamedKey::Info => new::Key::Info,
            old::NamedKey::InstantReplay => new::Key::InstantReplay,
            old::NamedKey::Link => new::Key::Link,
            old::NamedKey::ListProgram => new::Key::ListProgram,
            old::NamedKey::LiveContent => new::Key::LiveContent,
            old::NamedKey::Lock => new::Key::Lock,
            old::NamedKey::MediaApps => new::Key::MediaApps,
            old::NamedKey::MediaAudioTrack => new::Key::MediaAudioTrack,
            old::NamedKey::MediaLast => new::Key::MediaLast,
            old::NamedKey::MediaSkipBackward => new::Key::MediaSkipBackward,
            old::NamedKey::MediaSkipForward => new::Key::MediaSkipForward,
            old::NamedKey::MediaStepBackward => new::Key::MediaStepBackward,
            old::NamedKey::MediaStepForward => new::Key::MediaStepForward,
            old::NamedKey::MediaTopMenu => new::Key::MediaTopMenu,
            old::NamedKey::NavigateIn => new::Key::NavigateIn,
            old::NamedKey::NavigateNext => new::Key::NavigateNext,
            old::NamedKey::NavigateOut => new::Key::NavigateOut,
            old::NamedKey::NavigatePrevious => new::Key::NavigatePrevious,
            old::NamedKey::NextFavoriteChannel => new::Key::NextFavoriteChannel,
            old::NamedKey::NextUserProfile => new::Key::NextUserProfile,
            old::NamedKey::OnDemand => new::Key::OnDemand,
            old::NamedKey::Pairing => new::Key::Pairing,
            old::NamedKey::PinPDown => new::Key::PinPDown,
            old::NamedKey::PinPMove => new::Key::PinPMove,
            old::NamedKey::PinPToggle => new::Key::PinPToggle,
            old::NamedKey::PinPUp => new::Key::PinPUp,
            old::NamedKey::PlaySpeedDown => new::Key::PlaySpeedDown,
            old::NamedKey::PlaySpeedReset => new::Key::PlaySpeedReset,
            old::NamedKey::PlaySpeedUp => new::Key::PlaySpeedUp,
            old::NamedKey::RandomToggle => new::Key::RandomToggle,
            old::NamedKey::RcLowBattery => new::Key::RcLowBattery,
            old::NamedKey::RecordSpeedNext => new::Key::RecordSpeedNext,
            old::NamedKey::RfBypass => new::Key::RfBypass,
            old::NamedKey::ScanChannelsToggle => new::Key::ScanChannelsToggle,
            old::NamedKey::ScreenModeNext => new::Key::ScreenModeNext,
            old::NamedKey::Settings => new::Key::Settings,
            old::NamedKey::SplitScreenToggle => new::Key::SplitScreenToggle,
            old::NamedKey::STBInput => new::Key::STBInput,
            old::NamedKey::STBPower => new::Key::STBPower,
            old::NamedKey::Subtitle => new::Key::Subtitle,
            old::NamedKey::Teletext => new::Key::Teletext,
            old::NamedKey::VideoModeNext => new::Key::VideoModeNext,
            old::NamedKey::Wink => new::Key::Wink,
            old::NamedKey::ZoomToggle => new::Key::ZoomToggle,
            old::NamedKey::F1 => new::Key::F1,
            old::NamedKey::F2 => new::Key::F2,
            old::NamedKey::F3 => new::Key::F3,
            old::NamedKey::F4 => new::Key::F4,
            old::NamedKey::F5 => new::Key::F5,
            old::NamedKey::F6 => new::Key::F6,
            old::NamedKey::F7 => new::Key::F7,
            old::NamedKey::F8 => new::Key::F8,
            old::NamedKey::F9 => new::Key::F9,
            old::NamedKey::F10 => new::Key::F10,
            old::NamedKey::F11 => new::Key::F11,
            old::NamedKey::F12 => new::Key::F12,
            old::NamedKey::F13 => new::Key::F13,
            old::NamedKey::F14 => new::Key::F14,
            old::NamedKey::F15 => new::Key::F15,
            old::NamedKey::F16 => new::Key::F16,
            old::NamedKey::F17 => new::Key::F17,
            old::NamedKey::F18 => new::Key::F18,
            old::NamedKey::F19 => new::Key::F19,
            old::NamedKey::F20 => new::Key::F20,
            old::NamedKey::F21 => new::Key::F21,
            old::NamedKey::F22 => new::Key::F22,
            old::NamedKey::F23 => new::Key::F23,
            old::NamedKey::F24 => new::Key::F24,
            old::NamedKey::F25 => new::Key::F25,
            old::NamedKey::F26 => new::Key::F26,
            old::NamedKey::F27 => new::Key::F27,
            old::NamedKey::F28 => new::Key::F28,
            old::NamedKey::F29 => new::Key::F29,
            old::NamedKey::F30 => new::Key::F30,
            old::NamedKey::F31 => new::Key::F31,
            old::NamedKey::F32 => new::Key::F32,
            old::NamedKey::F33 => new::Key::F33,
            old::NamedKey::F34 => new::Key::F34,
            old::NamedKey::F35 => new::Key::F35,
            // `NamedKey` is #[non_exhaustive]
            _ => new::Key::Unidentified,
        }
    }

    /// Convert a v0.8 [`Code`](old::Code) to a v0.7 [`Code`](new::Code).
    ///
    /// Variants that do not exist in v0.7 are mapped to [`Code::Unidentified`](new::Code::Unidentified).
    #[allow(deprecated)]
    pub fn code(code: old::Code) -> new::Code {
        match code {
            old::Code::Backquote => new::Code::Backquote,
            old::Code::Backslash => new::Code::Backslash,
            old::Code::BracketLeft => new::Code::BracketLeft,
            old::Code::BracketRight => new::Code::BracketRight,
            old::Code::Comma => new::Code::Comma,
            old::Code::Digit0 => new::Code::Digit0,
            old::Code::Digit1 => new::Code::Digit1,
            old::Code::Digit2 => new::Code::Digit2,
            old::Code::Digit3 => new::Code::Digit3,
            old::Code::Digit4 => new::Code::Digit4,
            old::Code::Digit5 => new::Code::Digit5,
            old::Code::Digit6 => new::Code::Digit6,
            old::Code::Digit7 => new::Code::Digit7,
            old::Code::Digit8 => new::Code::Digit8,
            old::Code::Digit9 => new::Code::Digit9,
            old::Code::Equal => new::Code::Equal,
            old::Code::IntlBackslash => new::Code::IntlBackslash,
            old::Code::IntlRo => new::Code::IntlRo,
            old::Code::IntlYen => new::Code::IntlYen,
            old::Code::KeyA => new::Code::KeyA,
            old::Code::KeyB => new::Code::KeyB,
            old::Code::KeyC => new::Code::KeyC,
            old::Code::KeyD => new::Code::KeyD,
            old::Code::KeyE => new::Code::KeyE,
            old::Code::KeyF => new::Code::KeyF,
            old::Code::KeyG => new::Code::KeyG,
            old::Code::KeyH => new::Code::KeyH,
            old::Code::KeyI => new::Code::KeyI,
            old::Code::KeyJ => new::Code::KeyJ,
            old::Code::KeyK => new::Code::KeyK,
            old::Code::KeyL => new::Code::KeyL,
            old::Code::KeyM => new::Code::KeyM,
            old::Code::KeyN => new::Code::KeyN,
            old::Code::KeyO => new::Code::KeyO,
            old::Code::KeyP => new::Code::KeyP,
            old::Code::KeyQ => new::Code::KeyQ,
            old::Code::KeyR => new::Code::KeyR,
            old::Code::KeyS => new::Code::KeyS,
            old::Code::KeyT => new::Code::KeyT,
            old::Code::KeyU => new::Code::KeyU,
            old::Code::KeyV => new::Code::KeyV,
            old::Code::KeyW => new::Code::KeyW,
            old::Code::KeyX => new::Code::KeyX,
            old::Code::KeyY => new::Code::KeyY,
            old::Code::KeyZ => new::Code::KeyZ,
            old::Code::Minus => new::Code::Minus,
            old::Code::Period => new::Code::Period,
            old::Code::Quote => new::Code::Quote,
            old::Code::Semicolon => new::Code::Semicolon,
            old::Code::Slash => new::Code::Slash,
            old::Code::AltLeft => new::Code::AltLeft,
            old::Code::AltRight => new::Code::AltRight,
            old::Code::Backspace => new::Code::Backspace,
            old::Code::CapsLock => new::Code::CapsLock,
            old::Code::ContextMenu => new::Code::ContextMenu,
            old::Code::ControlLeft => new::Code::ControlLeft,
            old::Code::ControlRight => new::Code::ControlRight,
            old::Code::Enter => new::Code::Enter,
            old::Code::MetaLeft => new::Code::MetaLeft,
            old::Code::MetaRight => new::Code::MetaRight,
            old::Code::ShiftLeft => new::Code::ShiftLeft,
            old::Code::ShiftRight => new::Code::ShiftRight,
            old::Code::Space => new::Code::Space,
            old::Code::Tab => new::Code::Tab,
            old::Code::Convert => new::Code::Convert,
            old::Code::KanaMode => new::Code::KanaMode,
            old::Code::Lang1 => new::Code::Lang1,
            old::Code::Lang2 => new::Code::Lang2,
            old::Code::Lang3 => new::Code::Lang3,
            old::Code::Lang4 => new::Code::Lang4,
            old::Code::Lang5 => new::Code::Lang5,
            old::Code::NonConvert => new::Code::NonConvert,
            old::Code::Delete => new::Code::Delete,
            old::Code::End => new::Code::End,
            old::Code::Help => new::Code::Help,
            old::Code::Home => new::Code::Home,
            old::Code::Insert => new::Code::Insert,
            old::Code::PageDown => new::Code::PageDown,
            old::Code::PageUp => new::Code::PageUp,
            old::Code::ArrowDown => new::Code::ArrowDown,
            old::Code::ArrowLeft => new::Code::ArrowLeft,
            old::Code::ArrowRight => new::Code::ArrowRight,
            old::Code::ArrowUp => new::Code::ArrowUp,
            old::Code::NumLock => new::Code::NumLock,
            old::Code::Numpad0 => new::Code::Numpad0,
            old::Code::Numpad1 => new::Code::Numpad1,
            old::Code::Numpad2 => new::Code::Numpad2,
            old::Code::Numpad3 => new::Code::Numpad3,
            old::Code::Numpad4 => new::Code::Numpad4,
            old::Code::Numpad5 => new::Code::Numpad5,
            old::Code::Numpad6 => new::Code::Numpad6,
            old::Code::Numpad7 => new::Code::Numpad7,
            old::Code::Numpad8 => new::Code::Numpad8,
            old::Code::Numpad9 => new::Code::Numpad9,
            old::Code::NumpadAdd => new::Code::NumpadAdd,
            old::Code::NumpadBackspace => new::Code::NumpadBackspace,
            old::Code::NumpadClear => new::Code::NumpadClear,
            old::Code::NumpadClearEntry => new::Code::NumpadClearEntry,
            old::Code::NumpadComma => new::Code::NumpadComma,
            old::Code::NumpadDecimal => new::Code::NumpadDecimal,
            old::Code::NumpadDivide => new::Code::NumpadDivide,
            old::Code::NumpadEnter => new::Code::NumpadEnter,
            old::Code::NumpadEqual => new::Code::NumpadEqual,
            old::Code::NumpadHash => new::Code::NumpadHash,
            old::Code::NumpadMemoryAdd => new::Code::NumpadMemoryAdd,
            old::Code::NumpadMemoryClear => new::Code::NumpadMemoryClear,
            old::Code::NumpadMemoryRecall => new::Code::NumpadMemoryRecall,
            old::Code::NumpadMemoryStore => new::Code::NumpadMemoryStore,
            old::Code::NumpadMemorySubtract => new::Code::NumpadMemorySubtract,
            old::Code::NumpadMultiply => new::Code::NumpadMultiply,
            old::Code::NumpadParenLeft => new::Code::NumpadParenLeft,
            old::Code::NumpadParenRight => new::Code::NumpadParenRight,
            old::Code::NumpadStar => new::Code::NumpadStar,
            old::Code::NumpadSubtract => new::Code::NumpadSubtract,
            old::Code::Escape => new::Code::Escape,
            old::Code::Fn => new::Code::Fn,
            old::Code::FnLock => new::Code::FnLock,
            old::Code::PrintScreen => new::Code::PrintScreen,
            old::Code::ScrollLock => new::Code::ScrollLock,
            old::Code::Pause => new::Code::Pause,
            old::Code::BrowserBack => new::Code::BrowserBack,
            old::Code::BrowserFavorites => new::Code::BrowserFavorites,
            old::Code::BrowserForward => new::Code::BrowserForward,
            old::Code::BrowserHome => new::Code::BrowserHome,
            old::Code::BrowserRefresh => new::Code::BrowserRefresh,
            old::Code::BrowserSearch => new::Code::BrowserSearch,
            old::Code::BrowserStop => new::Code::BrowserStop,
            old::Code::Eject => new::Code::Eject,
            old::Code::LaunchApp1 => new::Code::LaunchApp1,
            old::Code::LaunchApp2 => new::Code::LaunchApp2,
            old::Code::LaunchMail => new::Code::LaunchMail,
            old::Code::MediaPlayPause => new::Code::MediaPlayPause,
            old::Code::MediaSelect => new::Code::MediaSelect,
            old::Code::MediaStop => new::Code::MediaStop,
            old::Code::MediaTrackNext => new::Code::MediaTrackNext,
            old::Code::MediaTrackPrevious => new::Code::MediaTrackPrevious,
            old::Code::Power => new::Code::Power,
            old::Code::Sleep => new::Code::Sleep,
            old::Code::AudioVolumeDown => new::Code::AudioVolumeDown,
            old::Code::AudioVolumeMute => new::Code::AudioVolumeMute,
            old::Code::AudioVolumeUp => new::Code::AudioVolumeUp,
            old::Code::WakeUp => new::Code::WakeUp,
            old::Code::Hyper => new::Code::Hyper,
            old::Code::Super => new::Code::Super,
            old::Code::Turbo => new::Code::Turbo,
            old::Code::Abort => new::Code::Abort,
            old::Code::Resume => new::Code::Resume,
            old::Code::Suspend => new::Code::Suspend,
            old::Code::Again => new::Code::Again,
            old::Code::Copy => new::Code::Copy,
            old::Code::Cut => new::Code::Cut,
            old::Code::Find => new::Code::Find,
            old::Code::Open => new::Code::Open,
            old::Code::Paste => new::Code::Paste,
            old::Code::Props => new::Code::Props,
            old::Code::Select => new::Code::Select,
            old::Code::Undo => new::Code::Undo,
            old::Code::Hiragana => new::Code::Hiragana,
            old::Code::Katakana => new::Code::Katakana,
            old::Code::Unidentified => new::Code::Unidentified,
            old::Code::F1 => new::Code::F1,
            old::Code::F2 => new::Code::F2,
            old::Code::F3 => new::Code::F3,
            old::Code::F4 => new::Code::F4,
            old::Code::F5 => new::Code::F5,
            old::Code::F6 => new::Code::F6,
            old::Code::F7 => new::Code::F7,
            old::Code::F8 => new::Code::F8,
            old::Code::F9 => new::Code::F9,
            old::Code::F10 => new::Code::F10,
            old::Code::F11 => new::Code::F11,
            old::Code::F12 => new::Code::F12,
            old::Code::F13 => new::Code::F13,
            old::Code::F14 => new::Code::F14,
            old::Code::F15 => new::Code::F15,
            old::Code::F16 => new::Code::F16,
            old::Code::F17 => new::Code::F17,
            old::Code::F18 => new::Code::F18,
            old::Code::F19 => new::Code::F19,
            old::Code::F20 => new::Code::F20,
            old::Code::F21 => new::Code::F21,
            old::Code::F22 => new::Code::F22,
            old::Code::F23 => new::Code::F23,
            old::Code::F24 => new::Code::F24,
            old::Code::F25 => new::Code::F25,
            old::Code::F26 => new::Code::F26,
            old::Code::F27 => new::Code::F27,
            old::Code::F28 => new::Code::F28,
            old::Code::F29 => new::Code::F29,
            old::Code::F30 => new::Code::F30,
            old::Code::F31 => new::Code::F31,
            old::Code::F32 => new::Code::F32,
            old::Code::F33 => new::Code::F33,
            old::Code::F34 => new::Code::F34,
            old::Code::F35 => new::Code::F35,
            old::Code::BrightnessDown => new::Code::BrightnessDown,
            old::Code::BrightnessUp => new::Code::BrightnessUp,
            old::Code::DisplayToggleIntExt => new::Code::DisplayToggleIntExt,
            old::Code::KeyboardLayoutSelect => new::Code::KeyboardLayoutSelect,
            old::Code::LaunchAssistant => new::Code::LaunchAssistant,
            old::Code::LaunchControlPanel => new::Code::LaunchControlPanel,
            old::Code::LaunchScreenSaver => new::Code::LaunchScreenSaver,
            old::Code::MailForward => new::Code::MailForward,
            old::Code::MailReply => new::Code::MailReply,
            old::Code::MailSend => new::Code::MailSend,
            old::Code::MediaFastForward => new::Code::MediaFastForward,
            old::Code::MediaPause => new::Code::MediaPause,
            old::Code::MediaPlay => new::Code::MediaPlay,
            old::Code::MediaRecord => new::Code::MediaRecord,
            old::Code::MediaRewind => new::Code::MediaRewind,
            old::Code::MicrophoneMuteToggle => new::Code::MicrophoneMuteToggle,
            old::Code::PrivacyScreenToggle => new::Code::PrivacyScreenToggle,
            old::Code::SelectTask => new::Code::SelectTask,
            old::Code::ShowAllWindows => new::Code::ShowAllWindows,
            old::Code::ZoomToggle => new::Code::ZoomToggle,
            old::Code::KeyboardBacklightToggle => new::Code::Unidentified,
            // `Code` is #[non_exhaustive]
            _ => new::Code::Unidentified,
        }
    }
}
