[package]
name = "blitz-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
url = "2.5.2"[package]
name = "blitz-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
url = "2.5.2"