name: macOS tests

on:
  push:
    branches:
      - master
    paths:
      - blitz_core/src/**
      - blitz_core/examples/**
      - blitz_core/Cargo.toml
      - examples/**
      - src/**
      - .github/**
      - Cargo.toml

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
    paths:
      - blitz_core/src/**
      - blitz_core/examples/**
      - blitz_core/Cargo.toml
      - examples/**
      - src/**
      - .github/**
      - Cargo.toml

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Test Suite
    runs-on: macos-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - run: cargo test --all --tests
