name: Publish Browser
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    # inputs:
    #   post:
    #     name: "Release Post"
    #     required: true
    #     description: Choose the release post to publish with. Must be a tag (eg v0.4.0)
    #     type: string
    #   channel:
    #     name: "CLI Binary Version"
    #     required: true
    #     description: Choose the version number to publish with. Must be a tag (ie v0.4.0)
    #     type: string

env:
  # make sure we have the right version
  # main is always a prepatch until we hit 1.0, and then this script needs to be updated
  # note that we need to promote the prepatch to a minor bump when we actually do a release
  # this means the version in git will always be one minor bump ahead of the actual release - basically meaning once
  # we release a version, it's fair game to merge breaking changes to main since all semver-compatible changes will be
  # backported automatically
  # SEMVER: ${{ github.event.inputs.channel == 'main' && 'prerelease' || 'patch' }}
  # PRERELEASE_TAG: ${{ github.event.inputs.channel == 'main' && '-pre' || '' }}
  RELEASE_TAG: ${{ github.event.inputs.channel }}
  RELEASE_POST: ${{ github.event.inputs.post }}

jobs:
  release-cli:
    permissions:
      contents: write
    runs-on: ${{ matrix.platform.os }}
    environment: Signed Builds
    name: ${{ matrix.platform.job_name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - job_name: Windows (x86_64)
            target: x86_64-pc-windows-msvc
            os: windows-latest
            use_git_cli: false
            artifact_name: "Blitz_0.0.0_windows_x86_64.exe"
            artifact_path: ./target/dx/blitz/bundle/windows/nsis/Blitz_0.0.0_x64-setup.exe
          - job_name: Windows (aarch64)
            target: aarch64-pc-windows-msvc
            os: windows-11-arm
            use_git_cli: false
            artifact_name: "Blitz_0.0.0_windows_aarch64.exe"
            artifact_path: ./target/dx/blitz/bundle/windows/nsis/Blitz_0.0.0_arm64-setup.exe
          - job_name: macOS (x86_64)
            target: x86_64-apple-darwin
            os: macos-15-intel
            use_git_cli: true
            artifact_name: "Blitz_0.0.0_macos_x86_64.dmg"
            artifact_path: "./target/dx/blitz/bundle/macos/macos/Blitz_0.0.0_x64.dmg"
          - job_name: macOS (aarch64)
            target: aarch64-apple-darwin
            os: macos-latest
            use_git_cli: true
            artifact_name: "Blitz_0.0.0_macos_aarch64.dmg"
            artifact_path: "./target/dx/blitz/bundle/macos/macos/Blitz_0.0.0_aarch64.dmg"
          - job_name: Linux (x86_64)
            target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            use_git_cli: false
            artifact_name: "Blitz_0.0.0_linux_x86_64.AppImage"
            artifact_path: ./target/dx/blitz/bundle/linux/appimage/blitz_0.0.0_x86_64.AppImage
          - job_name: Linux (aarch64)
            target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            use_git_cli: false
            artifact_name: "Blitz_0.0.0_linux_aarch64.AppImage"
            artifact_path: ./target/dx/blitz/bundle/linux/appimage/blitz_0.0.0_aarch64.AppImage
          # musl builds
          # - target: x86_64-unknown-linux-musl
          #   os: ubuntu-24.04
          # - target: aarch64-unknown-linux-musl
          #   os: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.92.0"
          targets: ${{ matrix.platform.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Create private key file
        if: ${{ matrix.platform.os == 'macos-15-intel' || matrix.platform.os == 'macos-latest' }}
        run: echo "${{ secrets.APPLE_API_KEY_CONTENT }}" > ${{ vars.APPLE_API_KEY_PATH }}

      - name: Install Dioxus CLI
        if: ${{ matrix.platform.use_git_cli == false }}
        uses: taiki-e/install-action@v2
        with:
          tool: dioxus-cli@0.7.7

      - name: Install Dioxus CLI (git)
        if: ${{ matrix.platform.use_git_cli == true }}
        run: cargo install dioxus-cli --git https://github.com/nicoburns/dioxus.git --rev=cccbd986706d348938c08928571be0e364786f65

      # - name: Install openssl on macos
      #   if: ${{ matrix.platform.os == 'macos-latest' || matrix.platform.os == 'macos-15-intel' }}
      #   run: brew install openssl

      # - name: Install nasm for windows (tls)
      #   if: ${{ matrix.platform.target == 'x86_64-pc-windows-msvc' }}
      #   uses: ilammy/setup-nasm@v1

      # - name: Free Disk Space
      #   if: ${{ matrix.platform.os == 'ubuntu-24.04' || matrix.platform.os == 'ubuntu-24.04-arm' }}
      #   uses: ./.github/actions/free-disk-space

      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: ${{ matrix.platform.os == 'ubuntu-24.04' || matrix.platform.os == 'ubuntu-24.04-arm' }}
        with:
          packages: libgtk-3-dev libxdo-dev libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libayatana-appindicator3-dev librsvg2-dev
          version: 1.0

      - name: Bundle browser
        run: dx bundle --package browser --profile production --locked --verbose --trace
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_API_ISSUER: ${{ vars.APPLE_API_ISSUER }}
          APPLE_API_KEY: ${{ vars.APPLE_API_KEY_ID }}
          APPLE_API_KEY_PATH: ${{ vars.APPLE_API_KEY_PATH }}

      - name: Delete private key file
        if: ${{ always() && (matrix.platform.os == 'macos-15-intel' || matrix.platform.os == 'macos-latest') }}
        run: rm ${{ vars.APPLE_API_KEY_PATH }}

      - name: Upload app bundle
        uses: actions/upload-artifact@v7
        if: ${{ matrix.platform.artifact_path != '' && matrix.platform.artifact_name != '' }}
        with:
          name: ${{ matrix.platform.artifact_name }}
          path: ${{ matrix.platform.artifact_path }}
          archive: false # Don't zip

      # # Todo: we want `cargo install dx` to actually just use a prebuilt binary instead of building it
      # - name: Build and upload CLI binaries
      #   uses: taiki-e/upload-rust-binary-action@v1
      #   with:
      #     bin: dx
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     target: ${{ matrix.platform.target }}
      #     archive: $bin-$target
      #     checksum: sha256
      #     manifest_path: packages/cli/Cargo.toml
      #     ref: refs/tags/${{ env.RELEASE_POST }}
      #     zip: "all"
